import { and, asc, desc, eq, inArray, isNull } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { writeAudit } from '@dentra/db/audit';
import { appointments, branches, dentistBranchAssignments, dentists, encounters, patients } from '@dentra/db/schema';
import { AuditAction } from '@dentra/shared';
import type { PatientActor } from './patients-service.js';
export type EncounterInput = { branchId: string; patientId: string; appointmentId?: string; date: string; chiefComplaint?: string; examination?: string; assessment?: string; procedures?: string; recommendations?: string; notes?: string; status: 'draft' | 'final' };
export type EncounterPatch = Partial<Omit<EncounterInput, 'patientId' | 'appointmentId'>> & { status?: 'draft' | 'final' };
export type ClinicEncountersService = { list: (clinicId: string, input: { patientId?: string; dentistId?: string }) => Promise<Array<Record<string, unknown>>>; get: (clinicId: string, encounterId: string) => Promise<Record<string, unknown> | null>; create: (clinicId: string, dentistId: string, input: EncounterInput, actor: PatientActor) => Promise<{ id: string; status: string }>; update: (clinicId: string, encounterId: string, dentistId: string, input: EncounterPatch, actor: PatientActor) => Promise<{ id: string; status: string }> };
export class ClinicEncounterError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
const selection = { id: encounters.id, clinicId: encounters.clinicId, branchId: encounters.branchId, branchName: branches.name, patientId: encounters.patientId, patientNumber: patients.patientNumber, patientFirstName: patients.firstName, patientLastName: patients.lastName, dentistId: encounters.dentistId, dentistFirstName: dentists.firstName, dentistLastName: dentists.lastName, appointmentId: encounters.appointmentId, date: encounters.date, chiefComplaint: encounters.chiefComplaint, examination: encounters.examination, assessment: encounters.assessment, procedures: encounters.procedures, recommendations: encounters.recommendations, notes: encounters.notes, status: encounters.status, createdBy: encounters.createdBy, createdAt: encounters.createdAt, updatedAt: encounters.updatedAt };
export function createClinicEncountersService(database: DB): ClinicEncountersService {
  const base = () => database.select(selection).from(encounters).innerJoin(branches, eq(encounters.branchId, branches.id)).innerJoin(patients, eq(encounters.patientId, patients.id)).leftJoin(dentists, eq(encounters.dentistId, dentists.id));
  const validate = async (clinicId: string, dentistId: string, input: Pick<EncounterInput, 'branchId' | 'patientId' | 'appointmentId'>) => {
    const [[patient], [assignment]] = await Promise.all([database.select({ id: patients.id }).from(patients).where(and(eq(patients.id, input.patientId), eq(patients.clinicId, clinicId), isNull(patients.deletedAt))).limit(1), database.select({ id: dentistBranchAssignments.id }).from(dentistBranchAssignments).innerJoin(branches, eq(dentistBranchAssignments.branchId, branches.id)).where(and(eq(dentistBranchAssignments.clinicId, clinicId), eq(dentistBranchAssignments.dentistId, dentistId), eq(dentistBranchAssignments.branchId, input.branchId), eq(dentistBranchAssignments.isActive, 'true'), eq(branches.isActive, true), isNull(branches.deletedAt))).limit(1)]);
    if (!patient) throw new ClinicEncounterError('PATIENT_NOT_FOUND', 'Patient not found', 404); if (!assignment) throw new ClinicEncounterError('BRANCH_ACCESS_REQUIRED', 'Dentist is not actively assigned to this branch', 403);
    if (input.appointmentId) { const [appointment] = await database.select({ id: appointments.id }).from(appointments).where(and(eq(appointments.id, input.appointmentId), eq(appointments.clinicId, clinicId), eq(appointments.patientId, input.patientId), eq(appointments.branchId, input.branchId), eq(appointments.dentistId, dentistId))).limit(1); if (!appointment) throw new ClinicEncounterError('APPOINTMENT_MISMATCH', 'Appointment does not match this patient, dentist, and branch', 409); }
  };
  return {
    list: async (clinicId, input) => base().where(and(eq(encounters.clinicId, clinicId), input.patientId ? eq(encounters.patientId, input.patientId) : undefined, input.dentistId ? eq(encounters.dentistId, input.dentistId) : undefined)).orderBy(desc(encounters.date), desc(encounters.createdAt)),
    get: async (clinicId, encounterId) => { const [row] = await base().where(and(eq(encounters.id, encounterId), eq(encounters.clinicId, clinicId))).limit(1); return row ?? null; },
    create: async (clinicId, dentistId, input, actor) => { await validate(clinicId, dentistId, input); return database.transaction(async (transaction) => { const [created] = await transaction.insert(encounters).values({ clinicId, dentistId, createdBy: actor.id, ...input, appointmentId: input.appointmentId || null }).returning({ id: encounters.id, status: encounters.status }); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'encounter', entityId: created.id, action: AuditAction.ENCOUNTER_CREATED, metadata: JSON.stringify({ patientId: input.patientId, branchId: input.branchId, appointmentId: input.appointmentId ?? null, status: input.status }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); if (input.status === 'final') await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'encounter', entityId: created.id, action: AuditAction.ENCOUNTER_FINALIZED, metadata: JSON.stringify({ fromStatus: 'draft', toStatus: 'final' }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return created; }); },
    update: async (clinicId, encounterId, dentistId, input, actor) => database.transaction(async (transaction) => { const [current] = await transaction.select({ id: encounters.id, status: encounters.status, patientId: encounters.patientId, branchId: encounters.branchId, dentistId: encounters.dentistId }).from(encounters).where(and(eq(encounters.id, encounterId), eq(encounters.clinicId, clinicId))).limit(1).for('update'); if (!current) throw new ClinicEncounterError('ENCOUNTER_NOT_FOUND', 'Encounter not found', 404); if (current.dentistId !== dentistId) throw new ClinicEncounterError('FORBIDDEN', 'Only the assigned dentist can edit this encounter', 403); if (current.status === 'final') throw new ClinicEncounterError('ENCOUNTER_FINAL', 'Finalized encounters are read-only', 409); const branchId = input.branchId ?? current.branchId; await validate(clinicId, dentistId, { branchId, patientId: current.patientId }); const nextStatus = input.status ?? current.status; const [updated] = await transaction.update(encounters).set({ ...input, branchId, status: nextStatus }).where(and(eq(encounters.id, encounterId), eq(encounters.clinicId, clinicId), eq(encounters.status, 'draft'))).returning({ id: encounters.id, status: encounters.status }); if (!updated) throw new ClinicEncounterError('ENCOUNTER_CONFLICT', 'Encounter changed before it could be saved', 409); const fields = Object.keys(input).filter((key) => key !== 'status'); if (fields.length) await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'encounter', entityId: encounterId, action: AuditAction.ENCOUNTER_UPDATED, metadata: JSON.stringify({ fields }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); if (nextStatus === 'final') await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'encounter', entityId: encounterId, action: AuditAction.ENCOUNTER_FINALIZED, metadata: JSON.stringify({ fromStatus: 'draft', toStatus: 'final' }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return updated; }),
  };
}
