import { and, asc, eq, isNull } from 'drizzle-orm'; import type { DB } from '@dentra/db'; import { writeAudit } from '@dentra/db/audit'; import { encounters, odontogramEvents, patients } from '@dentra/db/schema'; import { AuditAction } from '@dentra/shared'; import type { PatientActor } from './patients-service.js';
export type OdontogramInput = { toothNumber: string; surfaces: string; conditionCode?: string; procedureCode?: string; note?: string; encounterId?: string };
export type OdontogramEventView = { id: string; patientId: string; dentistId: string | null; encounterId: string | null; toothNumber: string; surfaces: string; conditionCode: string | null; procedureCode: string | null; note: string | null; correctionOf: string | null; createdAt: Date };
export type OdontogramResult = { events: OdontogramEventView[]; currentState: OdontogramEventView[] };
export type ClinicOdontogramService = { get: (clinicId: string, patientId: string) => Promise<OdontogramResult | null>; add: (clinicId: string, patientId: string, dentistId: string, input: OdontogramInput, actor: PatientActor) => Promise<{ id: string }>; correct: (clinicId: string, patientId: string, eventId: string, dentistId: string, input: OdontogramInput, actor: PatientActor) => Promise<{ id: string }> };
export class ClinicOdontogramError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
const eventSelection = { id: odontogramEvents.id, patientId: odontogramEvents.patientId, dentistId: odontogramEvents.dentistId, encounterId: odontogramEvents.encounterId, toothNumber: odontogramEvents.toothNumber, surfaces: odontogramEvents.surfaces, conditionCode: odontogramEvents.conditionCode, procedureCode: odontogramEvents.procedureCode, note: odontogramEvents.note, correctionOf: odontogramEvents.correctionOf, createdAt: odontogramEvents.createdAt };
function project(events: OdontogramEventView[]) { const superseded = new Set(events.flatMap((event) => event.correctionOf ? [event.correctionOf] : [])); const map = new Map<string, OdontogramEventView>(); events.filter((event) => !superseded.has(event.id)).forEach((event) => map.set(`${event.toothNumber}|${event.surfaces}`, event)); return Array.from(map.values()); }
export function createClinicOdontogramService(database: DB): ClinicOdontogramService {
  const patientExists = async (clinicId: string, patientId: string) => Boolean((await database.select({ id: patients.id }).from(patients).where(and(eq(patients.id, patientId), eq(patients.clinicId, clinicId), isNull(patients.deletedAt))).limit(1))[0]);
  const validateEncounter = async (clinicId: string, patientId: string, dentistId: string, encounterId?: string) => { if (!encounterId) return; const [row] = await database.select({ id: encounters.id }).from(encounters).where(and(eq(encounters.id, encounterId), eq(encounters.clinicId, clinicId), eq(encounters.patientId, patientId), eq(encounters.dentistId, dentistId))).limit(1); if (!row) throw new ClinicOdontogramError('ENCOUNTER_MISMATCH', 'Encounter does not match this patient and dentist', 409); };
  const insert = async (clinicId: string, patientId: string, dentistId: string, input: OdontogramInput, actor: PatientActor, correctionOf?: string) => database.transaction(async (transaction) => { const [created] = await transaction.insert(odontogramEvents).values({ clinicId, patientId, dentistId, encounterId: input.encounterId || null, toothNumber: input.toothNumber, surfaces: input.surfaces, conditionCode: input.conditionCode || null, procedureCode: input.procedureCode || null, note: input.note || null, correctionOf: correctionOf ?? null }).returning({ id: odontogramEvents.id }); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'odontogram_event', entityId: created.id, action: AuditAction.ODONTOGRAM_EVENT, metadata: JSON.stringify({ patientId, toothNumber: input.toothNumber, surfaces: input.surfaces, correctionOf: correctionOf ?? null, encounterId: input.encounterId ?? null }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return created; });
  return { get: async (clinicId, patientId) => { if (!(await patientExists(clinicId, patientId))) return null; const rows = await database.select(eventSelection).from(odontogramEvents).where(and(eq(odontogramEvents.clinicId, clinicId), eq(odontogramEvents.patientId, patientId))).orderBy(asc(odontogramEvents.createdAt)); return { events: rows, currentState: project(rows) }; }, add: async (clinicId, patientId, dentistId, input, actor) => { if (!(await patientExists(clinicId, patientId))) throw new ClinicOdontogramError('PATIENT_NOT_FOUND', 'Patient not found', 404); await validateEncounter(clinicId, patientId, dentistId, input.encounterId); return insert(clinicId, patientId, dentistId, input, actor); }, correct: async (clinicId, patientId, eventId, dentistId, input, actor) => { const [original] = await database.select(eventSelection).from(odontogramEvents).where(and(eq(odontogramEvents.id, eventId), eq(odontogramEvents.clinicId, clinicId), eq(odontogramEvents.patientId, patientId))).limit(1); if (!original) throw new ClinicOdontogramError('EVENT_NOT_FOUND', 'Odontogram event not found', 404); await validateEncounter(clinicId, patientId, dentistId, input.encounterId); return insert(clinicId, patientId, dentistId, input, actor, original.id); } };
}
