import { and, eq, asc } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { clinicMembershipPermissions, clinicMemberships, users } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction, PermissionKey, type ClinicRole } from '@dentra/shared';
export type PermissionActor = { id: string; email: string; ipAddress?: string; userAgent?: string };
export const permissionPresets: Record<ClinicRole, string[]> = { clinic_owner: Object.values(PermissionKey), clinic_admin: Object.values(PermissionKey), dentist: [PermissionKey.APPOINTMENTS, PermissionKey.PATIENTS, PermissionKey.CLINICAL_RECORDS, PermissionKey.REPORTS], receptionist: [PermissionKey.APPOINTMENTS, PermissionKey.PATIENTS], dental_assistant: [PermissionKey.APPOINTMENTS, PermissionKey.PATIENTS, PermissionKey.CLINICAL_RECORDS], cashier: [PermissionKey.BILLING_INVOICES, PermissionKey.BILLING_PAYMENTS], inventory_staff: [PermissionKey.INVENTORY] };
export type ClinicPermissionsService = ReturnType<typeof createClinicPermissionsService>;
export function createClinicPermissionsService(database: DB) { return {
  list: async (clinicId: string) => { const rows = await database.select({ membershipId: clinicMemberships.id, userId: users.id, name: users.name, email: users.email, role: clinicMemberships.role, branchId: clinicMemberships.branchId, permissionKey: clinicMembershipPermissions.permissionKey, isEnabled: clinicMembershipPermissions.isEnabled }).from(clinicMemberships).innerJoin(users, eq(clinicMemberships.userId, users.id)).leftJoin(clinicMembershipPermissions, eq(clinicMemberships.id, clinicMembershipPermissions.membershipId)).where(and(eq(clinicMemberships.clinicId, clinicId), eq(clinicMemberships.isActive, 'true'))).orderBy(asc(users.name)); const grouped = new Map<string, any>(); rows.forEach((row) => { const current = grouped.get(row.membershipId) ?? { membershipId: row.membershipId, userId: row.userId, name: row.name, email: row.email, role: row.role, branchId: row.branchId, permissions: new Set(permissionPresets[row.role]) }; if (row.permissionKey) { if (row.isEnabled) current.permissions.add(row.permissionKey); else current.permissions.delete(row.permissionKey); } grouped.set(row.membershipId, current); }); return [...grouped.values()].map((row) => ({ ...row, permissions: [...row.permissions] })); },
  update: async (clinicId: string, membershipId: string, permissionKey: string, isEnabled: boolean, actor: PermissionActor) => database.transaction(async (tx) => { const [membership] = await tx.select({ id: clinicMemberships.id, role: clinicMemberships.role }).from(clinicMemberships).where(and(eq(clinicMemberships.id, membershipId), eq(clinicMemberships.clinicId, clinicId), eq(clinicMemberships.isActive, 'true'))).limit(1); if (!membership) throw new Error('Membership not found'); const [updated] = await tx.insert(clinicMembershipPermissions).values({ clinicId, membershipId, permissionKey, isEnabled, updatedBy: actor.id }).onConflictDoUpdate({ target: [clinicMembershipPermissions.membershipId, clinicMembershipPermissions.permissionKey], set: { isEnabled, updatedBy: actor.id, updatedAt: new Date() } }).returning({ id: clinicMembershipPermissions.id }); await writeAudit(tx as unknown as DB, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'clinic_membership_permission', entityId: updated.id, action: AuditAction.PERMISSION_UPDATED, metadata: JSON.stringify({ membershipId, permissionKey, isEnabled }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return updated; }),
}; }
