import { and, asc, eq, gt, inArray, isNull, lt, ne, or } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { appointments, patients, recallRules, patientRecalls, services, treatmentRecords } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
import type { NotificationService } from '../notifications/service.js';

export type RecallActor = { id: string; email: string; ipAddress?: string; userAgent?: string };
export type RecallRuleInput = { serviceId: string; name: string; intervalDays: number; isActive?: boolean };
export type RecallService = ReturnType<typeof createRecallService>;

export class RecallError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }

export function createRecallService(database: DB, notifications?: NotificationService) {
  const audit = (tx: unknown, actor: RecallActor, clinicId: string, entityType: string, entityId: string, action: AuditAction, metadata: Record<string, unknown>) => writeAudit(tx as DB, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType, entityId, action, metadata: JSON.stringify(metadata), ipAddress: actor.ipAddress, userAgent: actor.userAgent });
  return {
    listRules: (clinicId: string) => database.select({ id: recallRules.id, serviceId: recallRules.serviceId, serviceName: services.name, name: recallRules.name, intervalDays: recallRules.intervalDays, isActive: recallRules.isActive, createdAt: recallRules.createdAt, updatedAt: recallRules.updatedAt }).from(recallRules).innerJoin(services, eq(recallRules.serviceId, services.id)).where(eq(recallRules.clinicId, clinicId)).orderBy(asc(services.name)),
    createRule: async (clinicId: string, input: RecallRuleInput, actor: RecallActor) => database.transaction(async (tx) => { const [service] = await tx.select({ id: services.id }).from(services).where(and(eq(services.id, input.serviceId), eq(services.clinicId, clinicId))).limit(1); if (!service) throw new RecallError('SERVICE_NOT_FOUND', 'Service not found', 404); const [created] = await tx.insert(recallRules).values({ clinicId, serviceId: input.serviceId, name: input.name, intervalDays: input.intervalDays, isActive: input.isActive === false ? 'false' : 'true' }).returning(); await audit(tx, actor, clinicId, 'recall_rule', created.id, AuditAction.RECALL_RULE_CREATED, { serviceId: input.serviceId, intervalDays: input.intervalDays }); return created; }),
    updateRule: async (clinicId: string, ruleId: string, input: Partial<RecallRuleInput>, actor: RecallActor) => database.transaction(async (tx) => { const [rule] = await tx.select().from(recallRules).where(and(eq(recallRules.id, ruleId), eq(recallRules.clinicId, clinicId))).limit(1); if (!rule) throw new RecallError('RULE_NOT_FOUND', 'Recall rule not found', 404); const [updated] = await tx.update(recallRules).set({ ...(input.serviceId ? { serviceId: input.serviceId } : {}), ...(input.name ? { name: input.name } : {}), ...(input.intervalDays ? { intervalDays: input.intervalDays } : {}), ...(input.isActive === undefined ? {} : { isActive: input.isActive ? 'true' : 'false' }), updatedAt: new Date() }).where(eq(recallRules.id, ruleId)).returning(); await audit(tx, actor, clinicId, 'recall_rule', ruleId, AuditAction.RECALL_RULE_UPDATED, { changed: Object.keys(input) }); return updated; }),
    createFromTreatment: async (clinicId: string, treatmentRecordId: string, actor: RecallActor) => database.transaction(async (tx) => { const [treatment] = await tx.select({ id: treatmentRecords.id, patientId: treatmentRecords.patientId, serviceId: treatmentRecords.serviceId, performedAt: treatmentRecords.performedAt }).from(treatmentRecords).where(and(eq(treatmentRecords.id, treatmentRecordId), eq(treatmentRecords.clinicId, clinicId))).limit(1); if (!treatment?.serviceId) return null; const [rule] = await tx.select().from(recallRules).where(and(eq(recallRules.clinicId, clinicId), eq(recallRules.serviceId, treatment.serviceId), eq(recallRules.isActive, 'true'))).limit(1); if (!rule) return null; const [existing] = await tx.select({ id: patientRecalls.id }).from(patientRecalls).where(eq(patientRecalls.treatmentRecordId, treatmentRecordId)).limit(1); if (existing) return existing; const dueAt = new Date((treatment.performedAt ?? new Date()).getTime() + rule.intervalDays * 86400000); const [created] = await tx.insert(patientRecalls).values({ clinicId, patientId: treatment.patientId, serviceId: treatment.serviceId, ruleId: rule.id, treatmentRecordId, dueAt, status: dueAt <= new Date() ? 'due' : 'upcoming' }).returning(); await audit(tx, actor, clinicId, 'patient_recall', created.id, AuditAction.RECALL_CREATED, { patientId: treatment.patientId, serviceId: treatment.serviceId, dueAt: dueAt.toISOString() }); return created; }),
    list: async (clinicId: string, status?: 'upcoming' | 'due' | 'contacted' | 'dismissed' | 'booked') => { const rows = await database.select({ id: patientRecalls.id, patientId: patientRecalls.patientId, patientFirstName: patients.firstName, patientLastName: patients.lastName, patientEmail: patients.email, serviceId: patientRecalls.serviceId, serviceName: services.name, treatmentRecordId: patientRecalls.treatmentRecordId, dueAt: patientRecalls.dueAt, status: patientRecalls.status, lastContactedAt: patientRecalls.lastContactedAt, dismissedAt: patientRecalls.dismissedAt, overrideReason: patientRecalls.overrideReason, bookedAppointmentId: patientRecalls.bookedAppointmentId }).from(patientRecalls).innerJoin(patients, and(eq(patientRecalls.patientId, patients.id), eq(patients.clinicId, clinicId), isNull(patients.deletedAt))).leftJoin(services, eq(patientRecalls.serviceId, services.id)).where(and(eq(patientRecalls.clinicId, clinicId), status ? eq(patientRecalls.status, status) : ne(patientRecalls.status, 'dismissed'))).orderBy(asc(patientRecalls.dueAt)); return rows.map((row) => ({ ...row, status: row.status === 'upcoming' && row.dueAt <= new Date() ? 'due' : row.status })); },
    contact: async (clinicId: string, recallId: string, actor: RecallActor) => { const result = await database.transaction(async (tx) => { const [row] = await tx.update(patientRecalls).set({ status: 'contacted', lastContactedAt: new Date(), updatedAt: new Date() }).where(and(eq(patientRecalls.id, recallId), eq(patientRecalls.clinicId, clinicId), or(eq(patientRecalls.status, 'upcoming'), eq(patientRecalls.status, 'due')))).returning(); if (!row) throw new RecallError('RECALL_NOT_FOUND', 'Recall is not available', 404); await audit(tx, actor, clinicId, 'patient_recall', recallId, AuditAction.RECALL_CONTACTED, {}); let notificationId: string | null = null; if (notifications) { const [patient] = await tx.select({ email: patients.email, firstName: patients.firstName }).from(patients).where(and(eq(patients.id, row.patientId), eq(patients.clinicId, clinicId))).limit(1); if (patient?.email) { const notification = await notifications.enqueue(tx as unknown as DB, { clinicId, channel: 'email', type: 'recall_reminder', recipient: patient.email, subject: 'Your dental follow-up reminder', body: `Hi ${patient.firstName}, your dental clinic has a follow-up reminder for you. Please contact the clinic to schedule your next visit.`, dedupeKey: `recall:${recallId}:${new Date().toISOString().slice(0, 10)}` }); notificationId = notification.id; } } return { row, notificationId }; }); if (result.notificationId) notifications?.attemptDelivery(result.notificationId); return result.row; },
    dismiss: async (clinicId: string, recallId: string, actor: RecallActor) => database.transaction(async (tx) => { const [row] = await tx.update(patientRecalls).set({ status: 'dismissed', dismissedAt: new Date(), updatedAt: new Date() }).where(and(eq(patientRecalls.id, recallId), eq(patientRecalls.clinicId, clinicId), ne(patientRecalls.status, 'booked'))).returning(); if (!row) throw new RecallError('RECALL_NOT_FOUND', 'Recall not found', 404); await audit(tx, actor, clinicId, 'patient_recall', recallId, AuditAction.RECALL_DISMISSED, {}); return row; }),
    overrideDueDate: async (clinicId: string, recallId: string, dueAt: string, reason: string, actor: RecallActor) => database.transaction(async (tx) => { const [row] = await tx.update(patientRecalls).set({ dueAt: new Date(dueAt), status: new Date(dueAt) <= new Date() ? 'due' : 'upcoming', overrideReason: reason, updatedAt: new Date() }).where(and(eq(patientRecalls.id, recallId), eq(patientRecalls.clinicId, clinicId), ne(patientRecalls.status, 'booked'))).returning(); if (!row) throw new RecallError('RECALL_NOT_FOUND', 'Recall not found', 404); await audit(tx, actor, clinicId, 'patient_recall', recallId, AuditAction.RECALL_OVERRIDDEN, { dueAt, reason }); return row; }),
    book: async (clinicId: string, recallId: string, input: { branchId: string; dentistId: string; startsAt: string; endsAt: string }, actor: RecallActor) => database.transaction(async (tx) => { const [recall] = await tx.select({ id: patientRecalls.id, patientId: patientRecalls.patientId, serviceId: patientRecalls.serviceId }).from(patientRecalls).where(and(eq(patientRecalls.id, recallId), eq(patientRecalls.clinicId, clinicId), ne(patientRecalls.status, 'dismissed'), ne(patientRecalls.status, 'booked'))).limit(1); if (!recall) throw new RecallError('RECALL_NOT_FOUND', 'Recall not found', 404); const [conflict] = await tx.select({ id: appointments.id }).from(appointments).where(and(eq(appointments.clinicId, clinicId), eq(appointments.dentistId, input.dentistId), inArray(appointments.status, ['pending', 'confirmed', 'checked_in', 'in_progress']), lt(appointments.startsAt, new Date(input.endsAt)), or(isNull(appointments.endsAt), gt(appointments.endsAt, new Date(input.startsAt))))).limit(1); if (conflict) throw new RecallError('SLOT_UNAVAILABLE', 'The selected dentist slot is unavailable', 409); const [appointment] = await tx.insert(appointments).values({ clinicId, branchId: input.branchId, dentistId: input.dentistId, serviceId: recall.serviceId, patientId: recall.patientId, status: 'confirmed', startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), bookedBy: actor.id, confirmedAt: new Date() }).returning({ id: appointments.id }); const [updated] = await tx.update(patientRecalls).set({ status: 'booked', bookedAppointmentId: appointment.id, updatedAt: new Date() }).where(eq(patientRecalls.id, recallId)).returning(); await audit(tx, actor, clinicId, 'patient_recall', recallId, AuditAction.RECALL_BOOKED, { appointmentId: appointment.id }); return { recall: updated, appointmentId: appointment.id }; }),
  };
}
