import { and, eq, gte, lte, sql } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { appointments, invoiceLineItems, invoicePayments, invoices, inventoryItems, inventoryTransactions, patients } from '@dentra/db/schema';
export type ReportRange = { from: Date; to: Date };
export function createClinicReportsService(database: DB) {
  return {
    operational: async (clinicId: string, range: ReportRange) => { const byStatus = await database.select({ status: appointments.status, count: sql<number>`count(*)::int` }).from(appointments).where(and(eq(appointments.clinicId, clinicId), gte(appointments.startsAt, range.from), lte(appointments.startsAt, range.to))).groupBy(appointments.status); const [registered] = await database.select({ count: sql<number>`count(*)::int` }).from(patients).where(and(eq(patients.clinicId, clinicId), gte(patients.createdAt, range.from), lte(patients.createdAt, range.to))); return { byStatus, patientsRegistered: registered?.count ?? 0 }; },
    financial: async (clinicId: string, range: ReportRange) => { const byMethod = await database.select({ paymentMethod: invoicePayments.paymentMethod, totalPhp: sql<string>`coalesce(sum(${invoicePayments.amountPhp}), 0)::numeric` }).from(invoicePayments).where(and(eq(invoicePayments.clinicId, clinicId), gte(invoicePayments.createdAt, range.from), lte(invoicePayments.createdAt, range.to))).groupBy(invoicePayments.paymentMethod); const [outstanding] = await database.select({ totalPhp: sql<string>`coalesce(sum(${invoices.totalAmountPhp}), 0)::numeric` }).from(invoices).where(and(eq(invoices.clinicId, clinicId), eq(invoices.status, 'pending'))); const byService = await database.select({ service: invoiceLineItems.description, totalPhp: sql<string>`coalesce(sum(${invoiceLineItems.totalPhp}), 0)::numeric` }).from(invoiceLineItems).innerJoin(invoices, and(eq(invoiceLineItems.invoiceId, invoices.id), eq(invoices.clinicId, clinicId))).where(and(gte(invoices.createdAt, range.from), lte(invoices.createdAt, range.to))).groupBy(invoiceLineItems.description); return { byMethod, byService, outstandingPhp: outstanding?.totalPhp ?? '0' }; },
    inventory: async (clinicId: string) => database.select({ itemId: inventoryItems.id, name: inventoryItems.name, unit: inventoryItems.unit, reorderLevel: inventoryItems.reorderLevel, currentStock: sql<string>`coalesce(sum(case when ${inventoryTransactions.direction} = 'out' then -${inventoryTransactions.quantity} else ${inventoryTransactions.quantity} end), 0)::numeric` }).from(inventoryItems).leftJoin(inventoryTransactions, and(eq(inventoryTransactions.itemId, inventoryItems.id), eq(inventoryTransactions.clinicId, clinicId))).where(eq(inventoryItems.clinicId, clinicId)).groupBy(inventoryItems.id),
  };
}
export type ClinicReportsService = ReturnType<typeof createClinicReportsService>;
