import { and, desc, eq, isNull } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { writeAudit } from '@dentra/db/audit';
import { branches, clinicGalleryItems, clinics } from '@dentra/db/schema';
import { AuditAction } from '@dentra/shared';
export type ClinicSettingsActor = { id: string; email: string; ipAddress?: string; userAgent?: string };
export type ClinicProfileInput = { heroText: string | null; description: string | null; email: string | null; phone: string | null; website: string | null; address: string | null; city: string | null; province: string | null; mapUrl: string | null; facebookUrl: string | null; instagramUrl: string | null; themePreset?: string; brandAccent?: string; showGallery?: boolean; showTeam?: boolean; showServices?: boolean; seoTitle?: string | null; seoDescription?: string | null; ogImageUrl?: string | null };
export type BranchLocationInput = { address: string | null; city: string | null; province: string | null; mapUrl: string | null };
export type ClinicSettings = ClinicProfileInput & { id: string; name: string; slug: string; publicationStatus: string; branches: Array<{ id: string; name: string; operatingHours: Record<string, string> } & BranchLocationInput>; gallery?: Array<{ id: string; imageUrl: string; altText: string; caption: string | null; sortOrder: string; isPublished: boolean }> };
export class ClinicSettingsError extends Error { constructor(public readonly code: 'CLINIC_NOT_FOUND' | 'BRANCH_NOT_FOUND', message: string) { super(message); this.name = 'ClinicSettingsError'; } }
export type ClinicSettingsService = { get: (clinicId: string) => Promise<ClinicSettings | null>; updateProfile: (clinicId: string, input: ClinicProfileInput, actor: ClinicSettingsActor) => Promise<{ id: string }>; updateBranchHours: (clinicId: string, branchId: string, hours: Record<string, string>, actor: ClinicSettingsActor) => Promise<{ id: string; operatingHours: Record<string, string> }>; updateBranchLocation: (clinicId: string, branchId: string, input: BranchLocationInput, actor: ClinicSettingsActor) => Promise<{ id: string }>; addGalleryItem?: (clinicId: string, input: { imageUrl: string; altText: string; caption?: string | null; sortOrder?: string }, actor: ClinicSettingsActor) => Promise<{ id: string }>; removeGalleryItem?: (clinicId: string, itemId: string, actor: ClinicSettingsActor) => Promise<{ id: string }> };
const parseHours = (value: string | null): Record<string, string> => { if (!value) return {}; try { const parsed: unknown = JSON.parse(value); return typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed) ? parsed as Record<string, string> : {}; } catch { return {}; } };
export function createClinicSettingsService(database: DB): ClinicSettingsService { return {
  get: async (clinicId) => { const [clinic] = await database.select({ id: clinics.id, name: clinics.name, slug: clinics.slug, publicationStatus: clinics.publicationStatus, heroText: clinics.heroText, description: clinics.description, email: clinics.email, phone: clinics.phone, website: clinics.website, address: clinics.address, city: clinics.city, province: clinics.province, mapUrl: clinics.mapUrl, facebookUrl: clinics.facebookUrl, instagramUrl: clinics.instagramUrl, themePreset: clinics.themePreset, brandAccent: clinics.brandAccent, showGallery: clinics.showGallery, showTeam: clinics.showTeam, showServices: clinics.showServices, seoTitle: clinics.seoTitle, seoDescription: clinics.seoDescription, ogImageUrl: clinics.ogImageUrl }).from(clinics).where(and(eq(clinics.id, clinicId), isNull(clinics.deletedAt))).limit(1); if (!clinic) return null; const [branchRows, gallery] = await Promise.all([database.select({ id: branches.id, name: branches.name, operatingHours: branches.operatingHours, address: branches.address, city: branches.city, province: branches.province, mapUrl: branches.mapUrl }).from(branches).where(and(eq(branches.clinicId, clinicId), eq(branches.isActive, true), isNull(branches.deletedAt))).orderBy(desc(branches.isMain), branches.name), database.select({ id: clinicGalleryItems.id, imageUrl: clinicGalleryItems.imageUrl, altText: clinicGalleryItems.altText, caption: clinicGalleryItems.caption, sortOrder: clinicGalleryItems.sortOrder, isPublished: clinicGalleryItems.isPublished }).from(clinicGalleryItems).where(eq(clinicGalleryItems.clinicId, clinicId))]); return { ...clinic, gallery, branches: branchRows.map((branch) => ({ ...branch, operatingHours: parseHours(branch.operatingHours) })) }; },
  updateProfile: async (clinicId, input, actor) => database.transaction(async (transaction) => { const [updated] = await transaction.update(clinics).set(input).where(and(eq(clinics.id, clinicId), isNull(clinics.deletedAt))).returning({ id: clinics.id }); if (!updated) throw new ClinicSettingsError('CLINIC_NOT_FOUND', 'Clinic not found'); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'clinic', entityId: clinicId, action: AuditAction.CLINIC_UPDATED, metadata: JSON.stringify({ fields: Object.keys(input) }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return updated; }),
  updateBranchHours: async (clinicId, branchId, hours, actor) => database.transaction(async (transaction) => { const [updated] = await transaction.update(branches).set({ operatingHours: JSON.stringify(hours) }).where(and(eq(branches.id, branchId), eq(branches.clinicId, clinicId), eq(branches.isActive, true), isNull(branches.deletedAt))).returning({ id: branches.id }); if (!updated) throw new ClinicSettingsError('BRANCH_NOT_FOUND', 'Clinic branch not found'); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'branch', entityId: branchId, action: AuditAction.BRANCH_UPDATED, metadata: JSON.stringify({ fields: ['operatingHours'] }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return { id: updated.id, operatingHours: hours }; }),
  updateBranchLocation: async (clinicId, branchId, input, actor) => database.transaction(async (transaction) => { const [updated] = await transaction.update(branches).set(input).where(and(eq(branches.id, branchId), eq(branches.clinicId, clinicId), eq(branches.isActive, true), isNull(branches.deletedAt))).returning({ id: branches.id }); if (!updated) throw new ClinicSettingsError('BRANCH_NOT_FOUND', 'Clinic branch not found'); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'branch', entityId: branchId, action: AuditAction.BRANCH_UPDATED, metadata: JSON.stringify({ fields: Object.keys(input) }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return updated; }),
  addGalleryItem: async (clinicId, input, actor) => database.transaction(async (transaction) => { const [created] = await transaction.insert(clinicGalleryItems).values({ clinicId, imageUrl: input.imageUrl, altText: input.altText, caption: input.caption ?? null, sortOrder: input.sortOrder ?? '0' }).returning({ id: clinicGalleryItems.id }); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'clinic_gallery_item', entityId: created.id, action: AuditAction.CLINIC_UPDATED, metadata: JSON.stringify({ fields: ['gallery'] }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return created; }),
  removeGalleryItem: async (clinicId, itemId, actor) => database.transaction(async (transaction) => { const [deleted] = await transaction.delete(clinicGalleryItems).where(and(eq(clinicGalleryItems.id, itemId), eq(clinicGalleryItems.clinicId, clinicId))).returning({ id: clinicGalleryItems.id }); if (!deleted) throw new ClinicSettingsError('BRANCH_NOT_FOUND', 'Gallery item not found'); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'clinic_gallery_item', entityId: itemId, action: AuditAction.CLINIC_UPDATED, metadata: JSON.stringify({ fields: ['gallery'] }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return deleted; }),
}; }
