import { and, desc, eq, isNull } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { writeAudit } from '@dentra/db/audit';
import { branches, clinics } from '@dentra/db/schema';
import { AuditAction } from '@dentra/shared';
export type ClinicSettingsActor = { id: string; email: string; ipAddress?: string; userAgent?: string };
export type ClinicProfileInput = { heroText: string | null; description: string | null; email: string | null; phone: string | null; website: string | null; address: string | null; city: string | null; province: string | null; mapUrl: string | null; facebookUrl: string | null; instagramUrl: string | null };
export type ClinicSettings = ClinicProfileInput & { id: string; name: string; slug: string; publicationStatus: string; branches: Array<{ id: string; name: string; operatingHours: Record<string, string> }> };
export class ClinicSettingsError extends Error { constructor(public readonly code: 'CLINIC_NOT_FOUND' | 'BRANCH_NOT_FOUND', message: string) { super(message); this.name = 'ClinicSettingsError'; } }
export type ClinicSettingsService = { get: (clinicId: string) => Promise<ClinicSettings | null>; updateProfile: (clinicId: string, input: ClinicProfileInput, actor: ClinicSettingsActor) => Promise<{ id: string }>; updateBranchHours: (clinicId: string, branchId: string, hours: Record<string, string>, actor: ClinicSettingsActor) => Promise<{ id: string; operatingHours: Record<string, string> }> };
const parseHours = (value: string | null): Record<string, string> => { if (!value) return {}; try { const parsed: unknown = JSON.parse(value); return typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed) ? parsed as Record<string, string> : {}; } catch { return {}; } };
export function createClinicSettingsService(database: DB): ClinicSettingsService { return {
  get: async (clinicId) => { const [clinic] = await database.select({ id: clinics.id, name: clinics.name, slug: clinics.slug, publicationStatus: clinics.publicationStatus, heroText: clinics.heroText, description: clinics.description, email: clinics.email, phone: clinics.phone, website: clinics.website, address: clinics.address, city: clinics.city, province: clinics.province, mapUrl: clinics.mapUrl, facebookUrl: clinics.facebookUrl, instagramUrl: clinics.instagramUrl }).from(clinics).where(and(eq(clinics.id, clinicId), isNull(clinics.deletedAt))).limit(1); if (!clinic) return null; const branchRows = await database.select({ id: branches.id, name: branches.name, operatingHours: branches.operatingHours }).from(branches).where(and(eq(branches.clinicId, clinicId), eq(branches.isActive, true), isNull(branches.deletedAt))).orderBy(desc(branches.isMain), branches.name); return { ...clinic, branches: branchRows.map((branch) => ({ ...branch, operatingHours: parseHours(branch.operatingHours) })) }; },
  updateProfile: async (clinicId, input, actor) => database.transaction(async (transaction) => { const [updated] = await transaction.update(clinics).set(input).where(and(eq(clinics.id, clinicId), isNull(clinics.deletedAt))).returning({ id: clinics.id }); if (!updated) throw new ClinicSettingsError('CLINIC_NOT_FOUND', 'Clinic not found'); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'clinic', entityId: clinicId, action: AuditAction.CLINIC_UPDATED, metadata: JSON.stringify({ fields: Object.keys(input) }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return updated; }),
  updateBranchHours: async (clinicId, branchId, hours, actor) => database.transaction(async (transaction) => { const [updated] = await transaction.update(branches).set({ operatingHours: JSON.stringify(hours) }).where(and(eq(branches.id, branchId), eq(branches.clinicId, clinicId), eq(branches.isActive, true), isNull(branches.deletedAt))).returning({ id: branches.id }); if (!updated) throw new ClinicSettingsError('BRANCH_NOT_FOUND', 'Clinic branch not found'); await writeAudit(transaction, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'branch', entityId: branchId, action: AuditAction.BRANCH_UPDATED, metadata: JSON.stringify({ fields: ['operatingHours'] }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return { id: updated.id, operatingHours: hours }; }),
}; }
