import { and, asc, eq, sql } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { clinicUsageCounters, packages, subscriptionChangeRequests } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';

export type SubscriptionActor = { id: string; email: string; ipAddress?: string; userAgent?: string };
export type SubscriptionOperationsService = ReturnType<typeof createSubscriptionOperationsService>;
export class SubscriptionOperationsError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }

export function createSubscriptionOperationsService(database: DB) {
  const audit = (tx: unknown, actor: SubscriptionActor, clinicId: string, entityId: string, action: AuditAction, metadata: Record<string, unknown>) => writeAudit(tx as unknown as DB, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'subscription_operation', entityId, action, metadata: JSON.stringify(metadata), ipAddress: actor.ipAddress, userAgent: actor.userAgent });
  return {
    listRequests: (clinicId: string) => database.select({ id: subscriptionChangeRequests.id, clinicId: subscriptionChangeRequests.clinicId, type: subscriptionChangeRequests.type, reason: subscriptionChangeRequests.reason, status: subscriptionChangeRequests.status, requestedPackageId: subscriptionChangeRequests.requestedPackageId, packageName: packages.name, requestedBy: subscriptionChangeRequests.requestedBy, reviewedAt: subscriptionChangeRequests.reviewedAt, reviewNote: subscriptionChangeRequests.reviewNote, createdAt: subscriptionChangeRequests.createdAt }).from(subscriptionChangeRequests).leftJoin(packages, eq(subscriptionChangeRequests.requestedPackageId, packages.id)).where(eq(subscriptionChangeRequests.clinicId, clinicId)).orderBy(asc(subscriptionChangeRequests.createdAt)),
    createRequest: async (clinicId: string, input: { type: 'upgrade' | 'downgrade' | 'addon'; requestedPackageId?: string; reason: string }, actor: SubscriptionActor) => database.transaction(async (tx) => { const [pending] = await tx.select({ id: subscriptionChangeRequests.id }).from(subscriptionChangeRequests).where(and(eq(subscriptionChangeRequests.clinicId, clinicId), eq(subscriptionChangeRequests.status, 'pending'))).limit(1); if (pending) throw new SubscriptionOperationsError('REQUEST_PENDING', 'A subscription request is already pending', 409); if (input.requestedPackageId) { const [pkg] = await tx.select({ id: packages.id }).from(packages).where(and(eq(packages.id, input.requestedPackageId), eq(packages.isActive, true))).limit(1); if (!pkg) throw new SubscriptionOperationsError('PACKAGE_NOT_AVAILABLE', 'Selected package is not available', 404); } const [created] = await tx.insert(subscriptionChangeRequests).values({ clinicId, type: input.type, requestedPackageId: input.requestedPackageId ?? null, reason: input.reason, requestedBy: actor.id }).returning({ id: subscriptionChangeRequests.id }); await audit(tx, actor, clinicId, created.id, AuditAction.SUBSCRIPTION_REQUESTED, { type: input.type, requestedPackageId: input.requestedPackageId ?? null }); return created; }),
    listPending: () => database.select({ id: subscriptionChangeRequests.id, clinicId: subscriptionChangeRequests.clinicId, type: subscriptionChangeRequests.type, reason: subscriptionChangeRequests.reason, status: subscriptionChangeRequests.status, requestedPackageId: subscriptionChangeRequests.requestedPackageId, packageName: packages.name, requestedBy: subscriptionChangeRequests.requestedBy, createdAt: subscriptionChangeRequests.createdAt }).from(subscriptionChangeRequests).leftJoin(packages, eq(subscriptionChangeRequests.requestedPackageId, packages.id)).where(eq(subscriptionChangeRequests.status, 'pending')).orderBy(asc(subscriptionChangeRequests.createdAt)),
    reviewRequest: async (requestId: string, input: { status: 'approved' | 'rejected'; note: string }, actor: SubscriptionActor) => database.transaction(async (tx) => { const [current] = await tx.select({ id: subscriptionChangeRequests.id, clinicId: subscriptionChangeRequests.clinicId, status: subscriptionChangeRequests.status }).from(subscriptionChangeRequests).where(eq(subscriptionChangeRequests.id, requestId)).limit(1).for('update'); if (!current) throw new SubscriptionOperationsError('REQUEST_NOT_FOUND', 'Subscription request not found', 404); if (current.status !== 'pending') throw new SubscriptionOperationsError('REQUEST_ALREADY_REVIEWED', 'Subscription request has already been reviewed', 409); const [updated] = await tx.update(subscriptionChangeRequests).set({ status: input.status, reviewedBy: actor.id, reviewedAt: new Date(), reviewNote: input.note, updatedAt: new Date() }).where(eq(subscriptionChangeRequests.id, requestId)).returning(); await audit(tx, actor, clinicIdOr(current.clinicId), requestId, AuditAction.SUBSCRIPTION_REVIEWED, { status: input.status }); return updated; }),
    usage: (clinicId: string, periodKey: string) => database.select({ metric: clinicUsageCounters.metric, periodKey: clinicUsageCounters.periodKey, used: clinicUsageCounters.used, limit: clinicUsageCounters.limit }).from(clinicUsageCounters).where(and(eq(clinicUsageCounters.clinicId, clinicId), eq(clinicUsageCounters.periodKey, periodKey))),
    incrementUsage: async (clinicId: string, metric: string, periodKey: string, amount: number, limit: number | null, actor?: SubscriptionActor) => database.transaction(async (tx) => { const [row] = await tx.insert(clinicUsageCounters).values({ clinicId, metric, periodKey, used: amount, limit }).onConflictDoUpdate({ target: [clinicUsageCounters.clinicId, clinicUsageCounters.metric, clinicUsageCounters.periodKey], set: { used: sql`${clinicUsageCounters.used} + ${amount}`, limit, updatedAt: new Date() } }).returning(); if (row && limit !== null && row.used > limit) throw new SubscriptionOperationsError('USAGE_LIMIT_REACHED', `Usage limit reached for ${metric}`, 402); if (actor) await audit(tx, actor, clinicId, row.id, AuditAction.USAGE_RECORDED, { metric, amount }); return row; }),
  };
}
function clinicIdOr(value: string): string { return value; }
