import type { Metadata } from 'next';
import Link from 'next/link';
import { Building2, ChevronLeft, ChevronRight, MapPin, Search, ShieldCheck, Stethoscope } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { getPublicClinics } from '@/lib/public-directory';

export const metadata: Metadata = { title: 'Dental Clinic Directory', description: 'Discover published dental clinics across the Philippines, explore their services, and book dental care.', openGraph: { title: 'Dental Clinic Directory | Dentra.ph', description: 'Find published dental clinics and services on Dentra.ph.', type: 'website' } };
type Props = { searchParams?: Record<string, string | string[] | undefined> };
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? '' : value ?? '';
function href(search: string, location: string, service: string, page: number) { const query = new URLSearchParams(); if (search) query.set('search', search); if (location) query.set('location', location); if (service) query.set('service', service); query.set('page', String(page)); return `/clinics?${query}`; }

export default async function ClinicsDirectory({ searchParams }: Props) {
  const search = one(searchParams?.search).trim().slice(0, 100); const location = one(searchParams?.location).trim().slice(0, 100); const service = one(searchParams?.service).trim().slice(0, 100); const parsed = Number.parseInt(one(searchParams?.page), 10); const page = parsed > 0 ? parsed : 1;
  let result; try { result = await getPublicClinics({ search, location, service, page }); } catch { result = { items: [], pagination: { page: 1, pageSize: 12, total: 0, totalPages: 1 } }; }
  return <><Navbar /><main className="min-h-screen bg-[#f8f7ff]"><section className="border-b border-violet-100 bg-white px-4 py-14 sm:px-6"><div className="mx-auto max-w-6xl"><p className="font-semibold text-violet-600">Clinic directory</p><h1 className="mt-2 text-4xl font-extrabold text-slate-950 sm:text-5xl">Find trusted dental care</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">Explore published clinic profiles, locations, services, and approved trust badges on Dentra.ph.</p></div></section><section className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
    <form className="grid gap-3 rounded-2xl border border-violet-100 bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_180px_auto]"><label className="relative"><span className="sr-only">Search clinics</span><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input name="search" defaultValue={search} placeholder="Clinic name" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100" /></label><label><span className="sr-only">Location</span><input name="location" defaultValue={location} placeholder="City or province" className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-violet-400" /></label><label><span className="sr-only">Service</span><input name="service" defaultValue={service} placeholder="Dental service" className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-violet-400" /></label><button className="h-11 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white hover:bg-violet-700">Search</button></form>
    <p className="mt-6 text-sm text-slate-500">{result.pagination.total} published clinic{result.pagination.total === 1 ? '' : 's'}</p>
    <div className="mt-4 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{result.items.map((clinic) => <article key={clinic.id} className="rounded-2xl border border-violet-100 bg-white p-5 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-violet-100"><Building2 className="text-violet-600" /></div><h2 className="mt-4 flex items-center gap-1.5 text-lg font-bold text-slate-900"><Link href={`/clinic/${clinic.slug}`} className="hover:text-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-400">{clinic.name}</Link>{clinic.verificationStatus === 'verified' && <ShieldCheck size={16} className="text-emerald-600" aria-label="Verified clinic" />}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{clinic.description ?? 'Professional dental care on Dentra.ph.'}</p><p className="mt-4 flex items-center gap-1.5 text-xs text-slate-500"><MapPin size={14} />{clinic.locations[0] || [clinic.city, clinic.province].filter(Boolean).join(', ') || 'Philippines'}</p><div className="mt-3 flex flex-wrap gap-1.5">{clinic.services.slice(0, 3).map((name) => <span key={name} className="rounded-full bg-violet-50 px-2 py-1 text-[11px] text-violet-700">{name}</span>)}</div></article>)}</div>
    {result.items.length === 0 && <div className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center"><Stethoscope className="mx-auto text-slate-300" /><h2 className="mt-3 font-semibold text-slate-700">No clinics found</h2><p className="mt-1 text-sm text-slate-500">Try broader search filters.</p></div>}
    <div className="mt-8 flex justify-center gap-3">{result.pagination.page > 1 && <Link href={href(search, location, service, result.pagination.page - 1)} className="inline-flex items-center gap-1 rounded-xl border bg-white px-4 py-2 text-sm"><ChevronLeft size={16} />Previous</Link>}{result.pagination.page < result.pagination.totalPages && <Link href={href(search, location, service, result.pagination.page + 1)} className="inline-flex items-center gap-1 rounded-xl border bg-white px-4 py-2 text-sm">Next<ChevronRight size={16} /></Link>}</div>
  </section></main><Footer /></>;
}
