import type { Metadata } from 'next';
import { Suspense } from 'react';
import Link from 'next/link';
import { Building2, CalendarCheck, CalendarX, ChevronLeft, ChevronRight, MapPin, Search, ShieldCheck, Stethoscope } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import NearMeButton from '@/components/public/NearMeButton';
import { getPublicClinics, type PublicClinic } from '@/lib/public-directory';

function clinicListJsonLd(items: PublicClinic[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    itemListElement: items.map((clinic, index) => ({ '@type': 'ListItem', position: index + 1, url: `https://dentra.ph/clinic/${clinic.slug}`, name: clinic.name })),
  };
}

export const metadata: Metadata = { title: 'Dental Clinic Directory', description: 'Discover published dental clinics across the Philippines, explore their services, and book dental care.', openGraph: { title: 'Dental Clinic Directory | Dentra.ph', description: 'Find published dental clinics and services on Dentra.ph.', type: 'website' } };
type Props = { searchParams?: Record<string, string | string[] | undefined> };
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? '' : value ?? '';
function href(search: string, location: string, service: string, page: number, geo?: { latitude: number; longitude: number; maxDistanceKm: number }) { const query = new URLSearchParams(); if (search) query.set('search', search); if (location) query.set('location', location); if (service) query.set('service', service); if (geo) { query.set('latitude', String(geo.latitude)); query.set('longitude', String(geo.longitude)); query.set('maxDistanceKm', String(geo.maxDistanceKm)); } query.set('page', String(page)); return `/clinics?${query}`; }

export default async function ClinicsDirectory({ searchParams }: Props) {
  const search = one(searchParams?.search).trim().slice(0, 100); const location = one(searchParams?.location).trim().slice(0, 100); const service = one(searchParams?.service).trim().slice(0, 100); const parsed = Number.parseInt(one(searchParams?.page), 10); const page = parsed > 0 ? parsed : 1;
  const rawLat = Number.parseFloat(one(searchParams?.latitude)); const rawLng = Number.parseFloat(one(searchParams?.longitude)); const rawRadius = Number.parseFloat(one(searchParams?.maxDistanceKm));
  const geo = Number.isFinite(rawLat) && Number.isFinite(rawLng) ? { latitude: rawLat, longitude: rawLng, maxDistanceKm: Number.isFinite(rawRadius) ? rawRadius : 25 } : undefined;
  let result; try { result = await getPublicClinics({ search, location, service, page, ...geo }); } catch { result = { items: [], pagination: { page: 1, pageSize: 12, total: 0, totalPages: 1 } }; }
  return <>{result.items.length > 0 && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(clinicListJsonLd(result.items)).replace(/</g, '\\u003c') }} />}<Navbar /><main className="min-h-screen bg-[#f8f7ff]"><section className="border-b border-violet-100 bg-white px-4 py-14 sm:px-6"><div className="mx-auto max-w-6xl"><p className="font-semibold text-violet-600">Clinic directory</p><h1 className="mt-2 text-4xl font-extrabold text-slate-950 sm:text-5xl">Find trusted dental care</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">Explore published clinic profiles, locations, services, and approved trust badges on Dentra.ph.</p></div></section><section className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
    <form className="grid gap-3 rounded-2xl border border-violet-100 bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_180px_auto]"><label className="relative"><span className="sr-only">Search clinics</span><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input name="search" defaultValue={search} placeholder="Clinic name" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100" /></label><label><span className="sr-only">Location</span><input name="location" defaultValue={location} placeholder="City or province" className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-violet-400" /></label><label><span className="sr-only">Service</span><input name="service" defaultValue={service} placeholder="Dental service" className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-violet-400" /></label><button className="h-11 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white hover:bg-violet-700">Search</button></form>
    <div className="mt-3"><Suspense fallback={<div className="h-11 w-32 rounded-xl border border-violet-100 bg-white" />}><NearMeButton /></Suspense></div>
    <p className="mt-6 text-sm text-slate-500">{result.pagination.total} published clinic{result.pagination.total === 1 ? '' : 's'}{geo && ` within ${geo.maxDistanceKm} km of you`}</p>
    <div className="mt-4 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{result.items.map((clinic) => <article key={clinic.id} className="rounded-2xl border border-violet-100 bg-white p-5 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-violet-100"><Building2 className="text-violet-600" /></div><h2 className="mt-4 flex items-center gap-2 text-lg font-bold text-slate-900"><Link href={`/clinic/${clinic.slug}`} className="hover:text-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-400">{clinic.name}</Link>{clinic.verificationStatus === 'verified' && <ShieldCheck size={16} className="text-emerald-600" aria-label="Verified clinic" />}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{clinic.description ?? 'Professional dental care on Dentra.ph.'}</p><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><MapPin size={14} />{clinic.locations[0] || [clinic.city, clinic.province].filter(Boolean).join(', ') || 'Philippines'}{typeof clinic.distanceKm === 'number' && <span className="text-slate-400">· {clinic.distanceKm.toFixed(1)} km away</span>}</p>{clinic.hasOpenSlotSoon ? <p className="mt-2 flex items-center gap-2 text-xs font-semibold text-emerald-700"><CalendarCheck size={13} /> Open slots this week</p> : <p className="mt-2 flex items-center gap-2 text-xs font-semibold text-slate-400"><CalendarX size={13} /> No open slots this week</p>}<div className="mt-3 flex flex-wrap gap-2">{clinic.services.slice(0, 3).map((name) => <span key={name} className="rounded-full bg-violet-50 px-2 py-1 text-[11px] text-violet-700">{name}</span>)}</div></article>)}</div>
    {result.items.length === 0 && <div className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center"><Stethoscope className="mx-auto text-slate-300" /><h2 className="mt-3 font-semibold text-slate-700">No clinics found</h2><p className="mt-1 text-sm text-slate-500">Try broader search filters.</p></div>}
    <div className="mt-8 flex justify-center gap-3">{result.pagination.page > 1 && <Link href={href(search, location, service, result.pagination.page - 1, geo)} className="inline-flex items-center gap-1 rounded-xl border bg-white px-4 py-2 text-sm"><ChevronLeft size={16} />Previous</Link>}{result.pagination.page < result.pagination.totalPages && <Link href={href(search, location, service, result.pagination.page + 1, geo)} className="inline-flex items-center gap-1 rounded-xl border bg-white px-4 py-2 text-sm">Next<ChevronRight size={16} /></Link>}</div>
  </section></main><Footer /></>;
}
