'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ChevronLeft, ChevronRight, ClipboardCheck, Loader2, Search } from 'lucide-react';
import { useAppBranch } from '@/components/app/AppBranchContext';

type Row = { id: string; encounterId: string; appointmentId: string | null; patientId: string; patientNumber: string; patientFirstName: string; patientLastName: string; branchId: string; branchName: string; serviceId: string | null; serviceName: string | null; workflowMode: 'quick' | 'standard' | null; toothRef: string | null; performedBy: string | null; dentistFirstName: string | null; dentistLastName: string | null; performedAt: string | null; createdAt: string };
type Options = { branches: Array<{ id: string; name: string }>; dentists: Array<{ id: string; firstName: string; lastName: string; branchId: string }>; services: Array<{ id: string; name: string }> };
const manilaDate = (date: Date) => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
const displayDate = (value: string | null) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(value)) : '—';

export default function TreatmentsListClient({ dentist = false }: { dentist?: boolean }) {
  const { clinicId, branchId } = useAppBranch(); const router = useRouter(); const searchParams = useSearchParams();
  const today = manilaDate(new Date()); const defaultFrom = manilaDate(new Date(Date.now() - 29 * 86_400_000));
  const selected = useMemo(() => ({ search: searchParams.get('search') ?? '', dateFrom: searchParams.get('dateFrom') ?? defaultFrom, dateTo: searchParams.get('dateTo') ?? today, branchId: searchParams.get('branchId') ?? branchId ?? '', dentistId: searchParams.get('dentistId') ?? '', serviceId: searchParams.get('serviceId') ?? '', workflowMode: searchParams.get('workflowMode') ?? '', page: Number(searchParams.get('page') ?? 1) }), [searchParams, defaultFrom, today, branchId]);
  const [form, setForm] = useState(selected); const [rows, setRows] = useState<Row[]>([]); const [pagination, setPagination] = useState({ page: 1, total: 0, totalPages: 1 }); const [options, setOptions] = useState<Options>({ branches: [], dentists: [], services: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => setForm(selected), [selected]);
  useEffect(() => { const query = new URLSearchParams({ clinicId, page: String(selected.page), pageSize: '20' }); Object.entries(selected).forEach(([key, value]) => { if (key !== 'page' && value) query.set(key, String(value)); }); setLoading(true); setError(''); fetch(`/api/clinic/treatments?${query}`, { cache: 'no-store' }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? 'Service records unavailable'); return payload.data; }).then((data) => { setRows(data.items); setPagination(data.pagination); }).catch((caught) => setError(caught instanceof Error ? caught.message : 'Service records unavailable')).finally(() => setLoading(false)); }, [clinicId, selected]);
  useEffect(() => { const query = new URLSearchParams({ clinicId }); if (branchId) query.set('branchId', branchId); fetch(`/api/clinic/appointment-options?${query}`, { cache: 'no-store' }).then((response) => response.json()).then((payload) => { if (payload.data) setOptions(payload.data); }).catch(() => undefined); }, [clinicId, branchId]);
  function apply(event: React.FormEvent) { event.preventDefault(); if (form.dateFrom > form.dateTo) { setError('Start date must be on or before end date.'); return; } const params = new URLSearchParams(); Object.entries({ ...form, page: 1 }).forEach(([key, value]) => { if (value) params.set(key, String(value)); }); router.replace(`/app/treatments?${params}`); }
  function page(value: number) { const params = new URLSearchParams(searchParams.toString()); params.set('page', String(value)); router.replace(`/app/treatments?${params}`); }
  const field = 'h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm';
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><div><p className="text-sm font-semibold text-violet-500">Clinic records</p><h1 className="mt-1 text-3xl font-bold text-violet-950">Service records</h1><p className="mt-1 text-sm text-slate-500">Completed treatments and quick services across the clinic.</p></div>
    <form onSubmit={apply} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><label className="relative sm:col-span-2"><span className="sr-only">Search records</span><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={form.search} onChange={(event) => setForm({ ...form, search: event.target.value })} placeholder="Patient number, patient, or service" className={`${field} w-full pl-9`} /></label><label className="text-xs font-semibold text-slate-600">From<input type="date" value={form.dateFrom} onChange={(event) => setForm({ ...form, dateFrom: event.target.value })} className={`${field} mt-1 w-full`} /></label><label className="text-xs font-semibold text-slate-600">To<input type="date" value={form.dateTo} onChange={(event) => setForm({ ...form, dateTo: event.target.value })} className={`${field} mt-1 w-full`} /></label><select aria-label="Branch" value={form.branchId} onChange={(event) => setForm({ ...form, branchId: event.target.value })} className={field}><option value="">All authorized branches</option>{options.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Dentist" value={form.dentistId} onChange={(event) => setForm({ ...form, dentistId: event.target.value })} className={field}><option value="">All dentists</option>{options.dentists.map((item) => <option key={item.id} value={item.id}>Dr. {item.firstName} {item.lastName}</option>)}</select><select aria-label="Service" value={form.serviceId} onChange={(event) => setForm({ ...form, serviceId: event.target.value })} className={field}><option value="">All services</option>{options.services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Workflow" value={form.workflowMode} onChange={(event) => setForm({ ...form, workflowMode: event.target.value })} className={field}><option value="">All workflows</option><option value="quick">Quick services</option><option value="standard">Standard encounters</option></select><div className="flex gap-2 lg:col-span-4"><button className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-bold text-white">Apply filters</button><Link href={`/app/treatments?dateFrom=${defaultFrom}&dateTo=${today}${branchId ? `&branchId=${encodeURIComponent(branchId)}` : ''}`} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600">Clear</Link></div></form>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <section className="overflow-hidden rounded-2xl border border-violet-100 bg-white shadow-sm">{loading ? <div className="flex justify-center py-16"><Loader2 className="animate-spin text-violet-600" /></div> : rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-violet-50 text-xs uppercase tracking-wide text-violet-700"><tr><th className="px-4 py-3">Performed</th><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Service</th><th className="px-4 py-3">Dentist</th><th className="px-4 py-3">Branch</th><th className="px-4 py-3">Area</th><th className="px-4 py-3">Links</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="hover:bg-violet-50/40"><td className="px-4 py-4 text-slate-600">{displayDate(row.performedAt ?? row.createdAt)}</td><td className="px-4 py-4"><Link href={`${dentist ? '/app/dentist/patients' : '/app/patients'}/${row.patientId}`} className="font-bold text-violet-800 hover:underline">{row.patientLastName}, {row.patientFirstName}</Link><p className="text-xs text-slate-500">{row.patientNumber}</p></td><td className="px-4 py-4"><p className="font-semibold text-slate-900">{row.serviceName ?? 'Dental service'}</p><span className={`text-xs font-semibold ${row.workflowMode === 'quick' ? 'text-emerald-700' : 'text-slate-500'}`}>{row.workflowMode === 'quick' ? 'Quick service' : 'Standard'}</span></td><td className="px-4 py-4 text-slate-600">{row.dentistFirstName ? `Dr. ${row.dentistFirstName} ${row.dentistLastName}` : '—'}</td><td className="px-4 py-4 text-slate-600">{row.branchName}</td><td className="px-4 py-4 text-slate-600">{row.toothRef ?? 'General'}</td><td className="px-4 py-4"><div className="flex gap-3"><Link href={`${dentist ? '/app/dentist/encounters' : '/app/encounters'}/${row.encounterId}`} className="font-semibold text-violet-700 hover:underline">Encounter</Link>{row.appointmentId && <Link href={`${dentist ? '/app/dentist/schedule' : '/app/appointments'}/${row.appointmentId}`} className="font-semibold text-violet-700 hover:underline">Appointment</Link>}</div></td></tr>)}</tbody></table></div> : <div className="flex flex-col items-center py-16 text-slate-500"><ClipboardCheck size={36} className="text-violet-200" /><p className="mt-3 font-semibold">No service records match these filters.</p></div>}</section>
    <div className="flex items-center justify-between text-sm text-slate-500"><span>{pagination.total} records · page {pagination.page} of {pagination.totalPages}</span><div className="flex gap-2"><button disabled={pagination.page <= 1} onClick={() => page(pagination.page - 1)} className="rounded-lg border bg-white p-2 disabled:opacity-40" aria-label="Previous page"><ChevronLeft size={18} /></button><button disabled={pagination.page >= pagination.totalPages} onClick={() => page(pagination.page + 1)} className="rounded-lg border bg-white p-2 disabled:opacity-40" aria-label="Next page"><ChevronRight size={18} /></button></div></div>
  </div>;
}
