'use client';
import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AlertCircle, ArrowLeft, FileCheck2, Loader2, ShieldCheck, Upload } from 'lucide-react';
type Submission = { id: string; status: 'pending' | 'approved' | 'rejected' | 'revoked'; documentTypes: string[]; documentCount: number; reviewReason: string | null; expiresAt: string | null; createdAt: string };
const clinicTypes = ['DOH/LGU permit', 'Business registration', 'Mayor’s permit', 'Other supporting document'];
const dentistTypes = ['PRC ID', 'PTR', 'S2 license', 'Other supporting document'];
const statusStyle = { pending: 'bg-amber-50 text-amber-700', approved: 'bg-emerald-50 text-emerald-700', rejected: 'bg-red-50 text-red-700', revoked: 'bg-slate-100 text-slate-700' };
export default function VerificationSubmissionClient({ clinicId, subjectType }: { clinicId: string; subjectType: 'clinic' | 'dentist' }) {
  const [items, setItems] = useState<Submission[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [files, setFiles] = useState<File[]>([]); const [types, setTypes] = useState<string[]>([]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/clinic/${clinicId}/verification?subjectType=${subjectType}`, { cache: 'no-store' }); const body = await response.json() as { success: boolean; data?: Submission[]; error?: { message?: string } }; if (!response.ok || !body.success) throw new Error(body.error?.message ?? 'Unable to load verification history'); setItems(body.data ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load verification history'); } finally { setLoading(false); } }, [clinicId, subjectType]);
  useEffect(() => { void load(); }, [load]);
  function chooseFiles(list: FileList | null) { const selected = Array.from(list ?? []).slice(0, 5); setFiles(selected); setTypes(selected.map((_, index) => types[index] ?? '')); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!files.length || types.some((type) => !type)) return setError('Attach at least one document and select every document type.'); setSaving(true); setError(null); setNotice(null); const form = new FormData(); form.set('subjectType', subjectType); form.set('documentTypes', JSON.stringify(types)); files.forEach((file) => form.append('file', file)); try { const response = await fetch(`/api/clinic/${clinicId}/verification`, { method: 'POST', body: form }); const body = await response.json() as { success: boolean; error?: { message?: string } }; if (!response.ok || !body.success) throw new Error(body.error?.message ?? 'Submission failed'); setFiles([]); setTypes([]); setNotice('Verification documents submitted for private review.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Submission failed'); } finally { setSaving(false); } }
  const pending = items.some((item) => item.status === 'pending'); const options = subjectType === 'clinic' ? clinicTypes : dentistTypes;
  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-4xl space-y-5"><header><Link href={subjectType === 'clinic' ? '/app/settings' : '/app/dentist/profile'} className="inline-flex items-center gap-1 text-sm text-violet-600"><ArrowLeft size={15} /> Back</Link><div className="mt-3 flex items-center gap-3"><div className="rounded-2xl bg-violet-100 p-3"><ShieldCheck className="text-violet-600" /></div><div><h1 className="text-2xl font-bold text-slate-900">{subjectType === 'clinic' ? 'Clinic' : 'Professional'} verification</h1><p className="text-sm text-slate-500">Documents remain private and are visible only to authorized reviewers.</p></div></div></header>{error && <div role="alert" className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={16} />{error}</div>}{notice && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <section className="rounded-2xl border border-violet-100 bg-white p-5"><h2 className="font-bold text-violet-900">Submission history</h2>{loading ? <div className="mt-4 flex items-center gap-2 text-sm text-violet-600"><Loader2 className="animate-spin" size={16} /> Loading…</div> : items.length ? <div className="mt-4 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-800">Submitted {new Date(item.createdAt).toLocaleDateString('en-PH')}</p><span className={`rounded-full px-2 py-1 text-xs font-semibold capitalize ${statusStyle[item.status]}`}>{item.status}</span></div><p className="mt-2 text-xs text-slate-500">{item.documentTypes.join(', ')} · {item.documentCount} private file{item.documentCount === 1 ? '' : 's'}</p>{item.reviewReason && <p className="mt-2 rounded-lg bg-slate-50 p-2 text-sm text-slate-700"><strong>Review reason:</strong> {item.reviewReason}</p>}{item.expiresAt && <p className="mt-2 text-xs text-slate-500">Expires {new Date(item.expiresAt).toLocaleDateString('en-PH')}</p>}</article>)}</div> : <p className="mt-3 text-sm text-slate-500">No verification submissions yet.</p>}</section>
    <form onSubmit={submit} className="rounded-2xl border border-violet-100 bg-white p-5"><h2 className="font-bold text-violet-900">Submit documents</h2>{pending ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">A submission is already pending. You can submit again after it is reviewed.</p> : <><p className="mt-1 text-xs text-slate-500">PDF, JPEG, PNG, or WebP · up to 10 MB each · maximum 5 files.</p><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-violet-200 p-6 text-sm font-semibold text-violet-700 hover:bg-violet-50"><Upload size={18} /> Choose private documents<input type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(event) => chooseFiles(event.target.files)} className="sr-only" /></label>{files.length > 0 && <div className="mt-4 space-y-3">{files.map((file, index) => <div key={`${file.name}-${index}`} className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-[1fr_14rem]"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-700">{file.name}</p><p className="text-xs text-slate-500">{(file.size / 1024 / 1024).toFixed(1)} MB</p></div><select required value={types[index] ?? ''} onChange={(event) => setTypes(types.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} className="h-10 rounded-lg border border-violet-200 bg-white px-3 text-sm"><option value="">Document type</option>{options.map((type) => <option key={type}>{type}</option>)}</select></div>)}</div>}<button disabled={saving || !files.length} className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white disabled:opacity-50">{saving ? <Loader2 size={16} className="animate-spin" /> : <FileCheck2 size={16} />}{saving ? 'Uploading…' : 'Submit for review'}</button></>}</form>
  </div></main>;
}
