import 'server-only';
import { cookies } from 'next/headers';
import { getBackendUrl } from './backend';
export type PatientListItem = { id: string; patientNumber: string; firstName: string; lastName: string; middleName: string | null; phone: string | null; email: string | null; status: string; lastAppointment: string | null; nextAppointment: string | null };
export type PatientDetail = { patient: { id: string; patientNumber: string; firstName: string; lastName: string; middleName: string | null; dateOfBirth: string | null; sex: string | null; civilStatus: string | null; occupation: string | null; nationality: string | null; phone: string | null; email: string | null; address: string | null; city: string | null; province: string | null; emergencyContactName: string | null; emergencyContactPhone: string | null; emergencyContactRelation: string | null; guardianName: string | null; guardianPhone: string | null; guardianRelation: string | null; status: string; notes: string | null }; appointments: Array<{ id: string; status: string; startsAt: string; endsAt: string | null; dentistFirstName: string | null; dentistLastName: string | null; serviceName: string | null; branchName: string; encounterId: string | null }>; medicalHistory: { current: MedicalHistory | null; versions: MedicalHistory[] }; dentalHistory: { current: DentalHistory | null; versions: DentalHistory[] } };
export type MedicalHistory = { id: string; allergies: string | null; currentMedications: string | null; majorConditions: string | null; isPregnant: string | null; physicianName: string | null; physicianPhone: string | null; notes: string | null; recordedByName: string | null; createdAt: string };
export type DentalHistory = { id: string; lastDentalVisit: string | null; previousTreatments: string | null; hasSensitivity: string | null; hasBleedingGums: string | null; hasPain: string | null; oralHabits: string | null; orthodonticHistory: string | null; chiefConcerns: string | null; notes: string | null; recordedByName: string | null; createdAt: string };
async function clinicGet<T>(path: string, params: Record<string, string | number>) { const url = getBackendUrl(path); Object.entries(params).forEach(([key, value]) => url.searchParams.set(key, String(value))); const response = await fetch(url, { headers: { cookie: cookies().toString() }, cache: 'no-store' }); if (!response.ok) throw new Error(`Clinic API failed with status ${response.status}`); return ((await response.json()) as { data: T }).data; }
export const getClinicPatients = (clinicId: string, search: string, page: number) => clinicGet<{ items: PatientListItem[]; pagination: { page: number; pageSize: number; total: number; totalPages: number } }>('/v1/clinic/patients', { clinicId, search, page });
export const getClinicPatientOptions = (clinicId: string) => clinicGet<{ items: PatientListItem[]; pagination: { page: number; pageSize: number; total: number; totalPages: number } }>('/v1/clinic/patients', { clinicId, search: '', page: 1, pageSize: 100 });
export const getClinicPatient = (clinicId: string, patientId: string, appointmentSort: 'asc' | 'desc' = 'desc') => clinicGet<PatientDetail>(`/v1/clinic/patients/${encodeURIComponent(patientId)}`, { clinicId, appointmentSort });
