import Link from 'next/link';
import { ChevronLeft, ChevronRight, CreditCard, Search } from 'lucide-react';
import { getAdminSubscriptions, type SubscriptionStatus } from '@/lib/admin-subscriptions';
import ClinicPackageAction from '@/components/admin/ClinicPackageAction';

type Props = { searchParams?: Record<string, string | string[] | undefined> };
const statuses: SubscriptionStatus[] = ['trial', 'active', 'past_due', 'cancelled', 'expired'];
const styles: Record<SubscriptionStatus, string> = { trial: 'bg-amber-50 text-amber-700', active: 'bg-emerald-50 text-emerald-700', past_due: 'bg-red-50 text-red-700', cancelled: 'bg-slate-100 text-slate-600', expired: 'bg-slate-100 text-slate-500' };
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? '' : value ?? '';
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(value)) : 'Open-ended';
function href(search: string, status: SubscriptionStatus | undefined, packageId: string | undefined, page: number) { const q = new URLSearchParams(); if (search) q.set('search', search); if (status) q.set('status', status); if (packageId) q.set('packageId', packageId); q.set('page', String(page)); return `/dentra-admin/subscriptions?${q}`; }

export default async function SubscriptionsPage({ searchParams }: Props) {
  const search = one(searchParams?.search).trim().slice(0, 100); const rawStatus = one(searchParams?.status); const status = statuses.includes(rawStatus as SubscriptionStatus) ? rawStatus as SubscriptionStatus : undefined; const packageId = one(searchParams?.packageId) || undefined; const parsed = Number.parseInt(one(searchParams?.page), 10); const page = parsed > 0 ? parsed : 1;
  let result; try { result = await getAdminSubscriptions({ search, status, packageId, page }); } catch { return <div className="p-6 sm:p-8"><div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h2 className="font-semibold">Unable to load subscriptions</h2><p className="mt-1 text-sm">Check that the API is running and refresh this page.</p></div></div>; }
  const first = result.pagination.total ? (result.pagination.page - 1) * result.pagination.pageSize + 1 : 0; const last = Math.min(result.pagination.page * result.pagination.pageSize, result.pagination.total);
  return <div className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-100"><CreditCard size={22} className="text-violet-600" /></div><div><h1 className="text-2xl font-bold text-slate-900">Subscriptions</h1><p className="text-sm text-slate-500">Review current and historical clinic package assignments.</p></div></div><p className="text-sm text-slate-500"><b className="text-slate-800">{result.pagination.total}</b> records</p></div>
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_170px_190px_auto]"><label className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input name="search" defaultValue={search} placeholder="Search clinic or package" className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm outline-none focus:border-violet-400" /></label><select name="status" defaultValue={status ?? ''} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">All statuses</option>{statuses.map((value) => <option key={value} value={value}>{value.replace('_', ' ')}</option>)}</select><select name="packageId" defaultValue={packageId ?? ''} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">All packages</option>{result.packageOptions.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select><div className="flex gap-2"><button className="h-11 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white">Apply</button>{(search || status || packageId) && <Link href="/dentra-admin/subscriptions" className="flex h-11 items-center rounded-xl border px-3 text-sm">Clear</Link>}</div></form>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{result.items.length === 0 ? <div className="flex min-h-64 items-center justify-center text-sm text-slate-500">No subscriptions match these filters.</div> : <div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Clinic', 'Package', 'Status', 'Starts', 'Expires', 'Action'].map((label) => <th key={label} className="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.items.map((item) => <tr key={item.id} className="hover:bg-violet-50/40"><td className="px-5 py-4"><Link href={`/dentra-admin/clinics/${item.clinicId}`} className="font-semibold text-slate-900 hover:text-violet-700">{item.clinicName}</Link><p className="text-xs text-slate-400">{item.clinicSlug}</p></td><td className="px-5 py-4 text-sm font-medium text-slate-700">{item.packageName}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${styles[item.status]}`}>{item.status.replace('_', ' ')}</span></td><td className="px-5 py-4 text-sm text-slate-600">{date(item.startsAt)}</td><td className="px-5 py-4 text-sm text-slate-600">{date(item.expiresAt)}</td><td className="px-5 py-4">{item.isCurrent ? <ClinicPackageAction clinicId={item.clinicId} clinicName={item.clinicName} currentPackageId={item.packageId} packages={result.assignmentPackageOptions} /> : <span className="text-xs text-slate-400">Historical</span>}</td></tr>)}</tbody></table></div>}
      <div className="flex items-center justify-between border-t px-5 py-4"><p className="text-sm text-slate-500">Showing {first}–{last} of {result.pagination.total}</p><div className="flex items-center gap-2">{result.pagination.page > 1 ? <Link href={href(search, status, packageId, result.pagination.page - 1)} className="inline-flex h-9 items-center gap-1 rounded-lg border px-3 text-sm"><ChevronLeft size={15} />Previous</Link> : null}<span className="text-sm text-slate-500">Page {result.pagination.page} of {result.pagination.totalPages}</span>{result.pagination.page < result.pagination.totalPages ? <Link href={href(search, status, packageId, result.pagination.page + 1)} className="inline-flex h-9 items-center gap-1 rounded-lg border px-3 text-sm">Next<ChevronRight size={15} /></Link> : null}</div></div>
    </div>
  </div></div>;
}
