import { randomBytes } from 'node:crypto';
import { and, eq } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { customDomains } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
export type DomainActor = { id: string; email: string };
export type DomainVerifier = { verify: (hostname: string, token: string) => Promise<boolean> };
export type CustomDomainService = ReturnType<typeof createCustomDomainService>;
export class CustomDomainError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
export function createCustomDomainService(database: DB, verifier: DomainVerifier = { verify: async () => false }) { return {
  add: async (clinicId: string, hostname: string, actor: DomainActor) => { const normalized = hostname.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/$/, ''); if (!/^(?:[a-z0-9-]+\.)+[a-z]{2,63}$/.test(normalized)) throw new CustomDomainError('INVALID_DOMAIN', 'Enter a valid hostname', 400); const token = `dentra-domain=${randomBytes(24).toString('hex')}`; const [created] = await database.insert(customDomains).values({ clinicId, hostname: normalized, verificationToken: token }).returning({ id: customDomains.id, hostname: customDomains.hostname, verificationToken: customDomains.verificationToken, status: customDomains.status }); await writeAudit(database, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'custom_domain', entityId: created.id, action: AuditAction.DOMAIN_ADDED, metadata: JSON.stringify({ hostname: normalized }) }); return { ...created, dnsRecord: { type: 'TXT', name: '_dentra-verification', value: token } }; },
  list: (clinicId: string) => database.select({ id: customDomains.id, hostname: customDomains.hostname, status: customDomains.status, verifiedAt: customDomains.verifiedAt, activatedAt: customDomains.activatedAt, lastCheckedAt: customDomains.lastCheckedAt, failureReason: customDomains.failureReason }).from(customDomains).where(eq(customDomains.clinicId, clinicId)),
  verify: async (clinicId: string, domainId: string, actor: DomainActor) => { const [domain] = await database.select().from(customDomains).where(and(eq(customDomains.id, domainId), eq(customDomains.clinicId, clinicId))).limit(1); if (!domain) throw new CustomDomainError('DOMAIN_NOT_FOUND', 'Custom domain not found', 404); const valid = await verifier.verify(domain.hostname, domain.verificationToken); const [updated] = await database.update(customDomains).set({ status: valid ? 'verified' : 'failed', verifiedAt: valid ? new Date() : null, lastCheckedAt: new Date(), failureReason: valid ? null : 'DNS verification record was not found', updatedAt: new Date() }).where(eq(customDomains.id, domainId)).returning({ id: customDomains.id, status: customDomains.status }); await writeAudit(database, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'custom_domain', entityId: domainId, action: valid ? AuditAction.DOMAIN_VERIFIED : AuditAction.DOMAIN_CHECKED, metadata: JSON.stringify({ status: updated.status }) }); return updated; },
  activate: async (clinicId: string, domainId: string, actor: DomainActor) => { const [updated] = await database.update(customDomains).set({ status: 'active', activatedAt: new Date(), updatedAt: new Date() }).where(and(eq(customDomains.id, domainId), eq(customDomains.clinicId, clinicId), eq(customDomains.status, 'verified'))).returning({ id: customDomains.id, status: customDomains.status }); if (!updated) throw new CustomDomainError('DOMAIN_NOT_VERIFIED', 'Verify DNS before activation', 409); await writeAudit(database, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'custom_domain', entityId: domainId, action: AuditAction.DOMAIN_ACTIVATED, metadata: JSON.stringify({}) }); return updated; },
}; }
