'use client';

import { useEffect, useState } from 'react';
import { BellRing, Check, Loader2, X } from 'lucide-react';

type Recall = { id: string; patientFirstName: string; patientLastName: string; serviceName: string | null; dueAt: string; status: string; lastContactedAt: string | null };

export default function RecallsClient({ clinicId }: { clinicId: string }) {
  const [rows, setRows] = useState<Recall[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const base = `/api/clinic/${clinicId}/recalls`;
  const load = async () => { setLoading(true); const response = await fetch(base, { credentials: 'include', cache: 'no-store' }); if (!response.ok) { setError('Unable to load the recall queue.'); setLoading(false); return; } setRows((await response.json()).data); setLoading(false); };
  useEffect(() => { void load(); }, [clinicId]);
  const action = async (id: string, endpoint: 'contact' | 'dismiss') => { const response = await fetch(`${base}/${id}/${endpoint}`, { method: 'POST', credentials: 'include' }); if (!response.ok) { setError('Unable to update this recall.'); return; } await load(); };
  return <div className="max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8"><div><h1 className="text-2xl font-bold text-slate-900">Recall queue</h1><p className="mt-1 text-sm text-slate-500">Review due follow-ups, contact patients, and keep preventive care on track.</p></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-2xl border border-violet-100 bg-white shadow-sm">{loading ? <div className="flex justify-center py-14"><Loader2 className="animate-spin text-violet-600" /></div> : rows.length === 0 ? <div className="flex flex-col items-center gap-2 py-14 text-slate-500"><BellRing size={32} className="text-violet-200" /><p className="text-sm">No active recalls.</p></div> : <ul className="divide-y divide-slate-100">{rows.map((row) => <li key={row.id} className="flex flex-wrap items-center justify-between gap-4 p-4 sm:p-5"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-slate-900">{row.patientFirstName} {row.patientLastName}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${row.status === 'due' ? 'bg-amber-50 text-amber-700' : 'bg-violet-50 text-violet-700'}`}>{row.status}</span></div><p className="mt-1 text-sm text-slate-600">{row.serviceName ?? 'Dental follow-up'} · due {new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(row.dueAt))}</p>{row.lastContactedAt && <p className="mt-1 text-xs text-slate-400">Last contacted {new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(row.lastContactedAt))}</p>}</div><div className="flex gap-2"><button onClick={() => void action(row.id, 'contact')} className="inline-flex items-center gap-1 rounded-lg bg-violet-600 px-3 py-2 text-sm font-semibold text-white"><Check size={15} /> Contact</button><button onClick={() => void action(row.id, 'dismiss')} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600"><X size={15} /> Dismiss</button></div></li>)}</ul>}</div></div>;
}
