import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { and, eq } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { invoicePayments, invoices, onlinePayments, paymentLinks, paymentWebhookEvents } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
export type PaymentService = ReturnType<typeof createPaymentService>;
export class PaymentError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
const hash = (value: string) => createHash('sha256').update(value).digest('hex');
function signaturesMatch(expected: string, received: string) {
  const expectedBytes = Buffer.from(expected, 'utf8');
  const receivedBytes = Buffer.from(received.trim(), 'utf8');
  return expectedBytes.length === receivedBytes.length && timingSafeEqual(expectedBytes, receivedBytes);
}
export function createPaymentService(database: DB, webhookSecret = process.env.DENTRA_PAYMENT_WEBHOOK_SECRET ?? 'development-payment-secret') { return {
  createLink: async (clinicId: string, invoiceId: string, expiresAt: Date, actor: { id: string; email: string }) => { const [invoice] = await database.select({ id: invoices.id, totalAmountPhp: invoices.totalAmountPhp, clinicId: invoices.clinicId }).from(invoices).where(and(eq(invoices.id, invoiceId), eq(invoices.clinicId, clinicId))).limit(1); if (!invoice) throw new PaymentError('INVOICE_NOT_FOUND', 'Invoice not found', 404); const raw = randomBytes(32).toString('base64url'); const [created] = await database.insert(paymentLinks).values({ clinicId, invoiceId, tokenHash: hash(raw), amountPhp: invoice.totalAmountPhp, expiresAt }).returning({ id: paymentLinks.id }); await writeAudit(database, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'payment_link', entityId: created.id, action: AuditAction.PAYMENT_LINK_CREATED, metadata: JSON.stringify({ invoiceId, expiresAt: expiresAt.toISOString() }) }); return { id: created.id, token: raw, amountPhp: invoice.totalAmountPhp, expiresAt }; },
  getLink: async (rawToken: string) => { const [link] = await database.select({ id: paymentLinks.id, clinicId: paymentLinks.clinicId, invoiceId: paymentLinks.invoiceId, amountPhp: paymentLinks.amountPhp, status: paymentLinks.status, expiresAt: paymentLinks.expiresAt, invoiceNumber: invoices.invoiceNumber }).from(paymentLinks).innerJoin(invoices, eq(paymentLinks.invoiceId, invoices.id)).where(eq(paymentLinks.tokenHash, hash(rawToken))).limit(1); if (!link) throw new PaymentError('LINK_NOT_FOUND', 'Payment link not found', 404); if (link.status === 'active' && link.expiresAt < new Date()) await database.update(paymentLinks).set({ status: 'expired', updatedAt: new Date() }).where(eq(paymentLinks.id, link.id)); return link; },
  verifySignature: (payload: string, signature: string) => createHmac('sha256', webhookSecret).update(payload).digest('hex') === signature,
  webhook: async (input: { eventId: string; eventType: string; provider: string; payload: string; signature: string; paymentId: string; linkToken: string; amountPhp: string; success: boolean }) => { if (!signaturesMatch(createHmac('sha256', webhookSecret).update(input.payload).digest('hex'), input.signature)) throw new PaymentError('INVALID_SIGNATURE', 'Webhook signature is invalid', 401); return database.transaction(async (tx) => { const [existing] = await tx.select({ id: paymentWebhookEvents.id }).from(paymentWebhookEvents).where(and(eq(paymentWebhookEvents.provider, input.provider), eq(paymentWebhookEvents.eventId, input.eventId))).limit(1); if (existing) return { duplicate: true }; await tx.insert(paymentWebhookEvents).values({ provider: input.provider, eventId: input.eventId, eventType: input.eventType, payload: input.payload, receivedAt: new Date() }); const [link] = await tx.select({ id: paymentLinks.id, clinicId: paymentLinks.clinicId, invoiceId: paymentLinks.invoiceId, amountPhp: paymentLinks.amountPhp, status: paymentLinks.status }).from(paymentLinks).where(eq(paymentLinks.tokenHash, hash(input.linkToken))).limit(1); if (!link) throw new PaymentError('LINK_NOT_FOUND', 'Payment link not found', 404); const status = input.success ? 'succeeded' : 'failed'; await tx.insert(onlinePayments).values({ clinicId: link.clinicId, invoiceId: link.invoiceId, linkId: link.id, provider: input.provider, providerPaymentId: input.paymentId, amountPhp: input.amountPhp, status, paidAt: input.success ? new Date() : null, failureReason: input.success ? null : 'Provider reported failure' }); if (input.success) { await tx.insert(invoicePayments).values({ invoiceId: link.invoiceId, clinicId: link.clinicId, amountPhp: input.amountPhp, paymentMethod: 'other', paymentDate: new Date().toISOString().slice(0, 10), recordedBy: null }); await tx.update(paymentLinks).set({ status: 'paid', updatedAt: new Date() }).where(eq(paymentLinks.id, link.id)); await tx.update(invoices).set({ status: 'paid', paidAt: new Date(), updatedAt: new Date() }).where(and(eq(invoices.id, link.invoiceId), eq(invoices.clinicId, link.clinicId))); } return { duplicate: false, status }; }); },
}; }
