import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { FeatureKey } from '@dentra/shared';
import { requireClinicFeature } from '../clinic/access.js';
import type { AuthServices, ClinicRole } from '../auth/types.js';
import type { EntitlementService } from '../entitlements/service.js';
import type { ClinicPermissionsService } from '../clinic/permissions-service.js';
import { postgresUuidSchema } from '../validation.js';
const clinic = z.object({ clinicId: postgresUuidSchema }); const member = z.object({ clinicId: postgresUuidSchema, membershipId: postgresUuidSchema }); const body = z.object({ permissionKey: z.string().trim().min(3).max(100), isEnabled: z.boolean() }).strict(); const roles: readonly ClinicRole[] = ['clinic_owner', 'clinic_admin'];
const actor = (request: FastifyRequest, auth: { user: { id: string; email: string } }) => ({ id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] });
export async function registerClinicPermissionRoutes(app: FastifyInstance, options: { auth: AuthServices; entitlements: EntitlementService; permissions: ClinicPermissionsService }) { app.get('/v1/clinic/:clinicId/staff/permissions', async (request, reply) => { const params = clinic.safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid clinic ID' } }); if (!await requireClinicFeature(request, reply, options, params.data.clinicId, FeatureKey.ROLES_MANAGE, [...roles])) return; return reply.send({ success: true, data: await options.permissions.list(params.data.clinicId) }); }); app.patch('/v1/clinic/:clinicId/staff/:membershipId/permissions', async (request, reply) => { const params = member.safeParse(request.params); const parsed = body.safeParse(request.body); if (!params.success || !parsed.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid permission change' } }); const auth = await requireClinicFeature(request, reply, options, params.data.clinicId, FeatureKey.ROLES_MANAGE, [...roles]); if (!auth) return; try { return reply.send({ success: true, data: await options.permissions.update(params.data.clinicId, params.data.membershipId, parsed.data.permissionKey, parsed.data.isEnabled, actor(request, auth)) }); } catch (caught) { return reply.status(404).send({ success: false, error: { code: 'MEMBERSHIP_NOT_FOUND', message: caught instanceof Error ? caught.message : 'Membership not found' } }); } }); }
