import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { FeatureKey } from '@dentra/shared';
import { requireClinicFeature } from '../clinic/access.js';
import { RecallError, type RecallService } from '../clinic/recall-service.js';
import type { AuthServices, ClinicRole } from '../auth/types.js';
import type { EntitlementService } from '../entitlements/service.js';
import { postgresUuidSchema } from '../validation.js';

const clinic = z.object({ clinicId: postgresUuidSchema });
const recall = z.object({ clinicId: postgresUuidSchema, recallId: postgresUuidSchema });
const rule = z.object({ serviceId: postgresUuidSchema, name: z.string().trim().min(2).max(200), intervalDays: z.number().int().min(1).max(3650), isActive: z.boolean().optional() }).strict();
const rulePatch = rule.partial().refine((value) => Object.keys(value).length > 0);
const override = z.object({ dueAt: z.string().datetime({ offset: true }), reason: z.string().trim().min(3).max(500) }).strict();
const booking = z.object({ branchId: postgresUuidSchema, dentistId: postgresUuidSchema, startsAt: z.string().datetime({ offset: true }), endsAt: z.string().datetime({ offset: true }) }).strict();
const manage: readonly ClinicRole[] = ['clinic_owner', 'clinic_admin', 'receptionist', 'dental_assistant', 'dentist'];

const actor = (request: FastifyRequest, auth: { user: { id: string; email: string } }) => ({ id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] });
const sendError = (reply: FastifyReply, caught: unknown) => { if (caught instanceof RecallError) return reply.status(caught.statusCode).send({ success: false, error: { code: caught.code, message: caught.message } }); throw caught; };

export async function registerClinicRecallRoutes(app: FastifyInstance, options: { auth: AuthServices; entitlements: EntitlementService; recalls: RecallService }) {
  const guard = (request: FastifyRequest, reply: FastifyReply, clinicId: string, roles: readonly ClinicRole[] = manage) => requireClinicFeature(request, reply, options, clinicId, FeatureKey.CLINICAL_RECORDS, [...roles]);
  app.get('/v1/clinic/:clinicId/recall-rules', async (request, reply) => { const params = clinic.safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid clinic ID' } }); if (!await guard(request, reply, params.data.clinicId, ['clinic_owner', 'clinic_admin', 'dentist'])) return; return reply.send({ success: true, data: await options.recalls.listRules(params.data.clinicId) }); });
  app.post('/v1/clinic/:clinicId/recall-rules', async (request, reply) => { const params = clinic.safeParse(request.params); const body = rule.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid recall rule' } }); const auth = await guard(request, reply, params.data.clinicId, ['clinic_owner', 'clinic_admin', 'dentist']); if (!auth) return; try { return reply.status(201).send({ success: true, data: await options.recalls.createRule(params.data.clinicId, body.data, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.patch('/v1/clinic/:clinicId/recall-rules/:ruleId', async (request, reply) => { const params = z.object({ clinicId: postgresUuidSchema, ruleId: postgresUuidSchema }).safeParse(request.params); const body = rulePatch.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid recall rule changes' } }); const auth = await guard(request, reply, params.data.clinicId, ['clinic_owner', 'clinic_admin', 'dentist']); if (!auth) return; try { return reply.send({ success: true, data: await options.recalls.updateRule(params.data.clinicId, params.data.ruleId, body.data, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.get('/v1/clinic/:clinicId/recalls', async (request, reply) => { const params = clinic.safeParse(request.params); const query = z.object({ status: z.enum(['upcoming', 'due', 'contacted', 'dismissed', 'booked']).optional() }).safeParse(request.query); if (!params.success || !query.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid recall filters' } }); if (!await guard(request, reply, params.data.clinicId)) return; return reply.send({ success: true, data: await options.recalls.list(params.data.clinicId, query.data.status) }); });
  app.post('/v1/clinic/:clinicId/recalls/:recallId/contact', async (request, reply) => { const params = recall.safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid recall ID' } }); const auth = await guard(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.recalls.contact(params.data.clinicId, params.data.recallId, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/clinic/:clinicId/recalls/:recallId/dismiss', async (request, reply) => { const params = recall.safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid recall ID' } }); const auth = await guard(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.recalls.dismiss(params.data.clinicId, params.data.recallId, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/clinic/:clinicId/recalls/:recallId/override', async (request, reply) => { const params = recall.safeParse(request.params); const body = override.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid recall override' } }); const auth = await guard(request, reply, params.data.clinicId, ['clinic_owner', 'clinic_admin', 'dentist']); if (!auth) return; try { return reply.send({ success: true, data: await options.recalls.overrideDueDate(params.data.clinicId, params.data.recallId, body.data.dueAt, body.data.reason, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/clinic/:clinicId/recalls/:recallId/book', async (request, reply) => { const params = recall.safeParse(request.params); const body = booking.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid follow-up appointment' } }); const auth = await guard(request, reply, params.data.clinicId); if (!auth) return; try { return reply.status(201).send({ success: true, data: await options.recalls.book(params.data.clinicId, params.data.recallId, body.data, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
}
