import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify'; import { z } from 'zod'; import type { AdminClinicSettingsService } from '../admin/clinic-settings-service.js'; import { ClinicSettingsError, type ClinicSettingsService } from '../clinic/settings-service.js'; import { hasClinicAccess } from '../auth/authorization.js'; import { resolveRequestAuthorization } from '../auth/request.js'; import type { AuthServices } from '../auth/types.js'; import { postgresUuidSchema } from '../validation.js';
const clinicParams = z.object({ clinicId: postgresUuidSchema }); const branchParams = clinicParams.extend({ branchId: postgresUuidSchema });
const optional = (max: number) => z.union([z.string().trim().max(max), z.null()]).optional().transform((value) => value || null);
const url = z.union([z.string().trim().url().max(500), z.literal(''), z.null()]).optional().transform((value) => value || null);
const profile = z.object({ heroText: optional(300), description: optional(5000), email: z.union([z.string().trim().email().max(255), z.literal(''), z.null()]).optional().transform((value) => value || null), phone: optional(20), website: url, address: optional(1000), city: optional(100), province: optional(100), mapUrl: url, facebookUrl: url, instagramUrl: url, themePreset: z.enum(['violet-clean', 'lavender-soft', 'midnight-violet']).optional(), brandAccent: z.string().regex(/^#(?:[0-9a-fA-F]{6})$/).optional(), showGallery: z.boolean().optional(), showTeam: z.boolean().optional(), showServices: z.boolean().optional(), seoTitle: optional(160), seoDescription: optional(320), ogImageUrl: url }).strict();
const gallery = z.object({ imageUrl: z.string().url().max(1000), altText: z.string().trim().min(3).max(200), caption: optional(500), sortOrder: z.string().regex(/^\d+$/).max(10).optional() }).strict();
const hours = z.object({ hours: z.array(z.object({ weekday: z.number().int().min(0).max(6), opensAt: z.number().int().min(0).max(1439).nullable(), closesAt: z.number().int().min(1).max(1440).nullable(), isClosed: z.boolean() })).max(7) }).strict();
const location = z.object({ address: optional(1000), city: optional(100), province: optional(100), mapUrl: url }).strict();
const publication = z.object({ publicationStatus: z.enum(['published', 'unpublished']) }).strict();
const closure = z.object({ branchId: postgresUuidSchema.nullable(), date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), label: z.string().trim().min(1).max(200) }).strict();
const closureEnabled = z.object({ isEnabled: z.boolean() }).strict();
export async function registerClinicSettingsRoutes(app: FastifyInstance, options: { auth: AuthServices; settings: ClinicSettingsService; publication: AdminClinicSettingsService }) {
  const authorize = async (request: FastifyRequest, reply: FastifyReply, clinicId: string) => { const auth = await resolveRequestAuthorization(request, options.auth); if (!auth) { reply.status(401).send({ success: false, error: { code: 'UNAUTHENTICATED', message: 'A valid session is required' } }); return null; } if (!hasClinicAccess(auth, clinicId, ['clinic_owner','clinic_admin'])) { reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic Owner or Admin access is required' } }); return null; } return auth; };
  app.get('/v1/clinic/:clinicId/settings', async (request, reply) => { const params = clinicParams.safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid clinic identifier' } }); if (!await authorize(request, reply, params.data.clinicId)) return; const data = await options.settings.get(params.data.clinicId); if (!data) return reply.status(404).send({ success: false, error: { code: 'CLINIC_NOT_FOUND', message: 'Clinic not found' } }); return reply.send({ success: true, data }); });
  app.patch('/v1/clinic/:clinicId/settings', async (request, reply) => { const params = clinicParams.safeParse(request.params); const body = profile.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid clinic profile details' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.settings.updateProfile(params.data.clinicId, body.data, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { if (!(error instanceof ClinicSettingsError)) throw error; return reply.status(404).send({ success: false, error: { code: error.code, message: error.message } }); } });
  app.patch('/v1/clinic/:clinicId/branches/:branchId/hours', async (request, reply) => { const params = branchParams.safeParse(request.params); const body = hours.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid operating hours' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.settings.updateBranchHours(params.data.clinicId, params.data.branchId, body.data.hours, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { if (!(error instanceof ClinicSettingsError)) throw error; return reply.status(error.code === 'INVALID_HOURS' ? 400 : 404).send({ success: false, error: { code: error.code, message: error.message } }); } });
  app.patch('/v1/clinic/:clinicId/branches/:branchId/location', async (request, reply) => { const params = branchParams.safeParse(request.params); const body = location.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid branch location details' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.settings.updateBranchLocation(params.data.clinicId, params.data.branchId, body.data, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { if (!(error instanceof ClinicSettingsError)) throw error; return reply.status(404).send({ success: false, error: { code: error.code, message: error.message } }); } });
  app.patch('/v1/clinic/:clinicId/publication', async (request, reply) => { const params = clinicParams.safeParse(request.params); const body = publication.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid publication change' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.publication.updatePublication(params.data.clinicId, body.data.publicationStatus, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { const value = error as { code?: string; message?: string }; return reply.status(value.code === 'CLINIC_NOT_FOUND' ? 404 : 409).send({ success: false, error: { code: value.code ?? 'PUBLICATION_ERROR', message: value.message ?? 'Unable to update publication' } }); } });
  app.post('/v1/clinic/:clinicId/gallery', async (request, reply) => { const params = clinicParams.safeParse(request.params); const body = gallery.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid gallery item' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; if (!options.settings.addGalleryItem) return reply.status(501).send({ success: false, error: { code: 'NOT_IMPLEMENTED', message: 'Gallery management is unavailable' } }); return reply.status(201).send({ success: true, data: await options.settings.addGalleryItem(params.data.clinicId, body.data, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); });
  app.delete('/v1/clinic/:clinicId/gallery/:itemId', async (request, reply) => { const params = clinicParams.extend({ itemId: postgresUuidSchema }).safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid gallery item' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; if (!options.settings.removeGalleryItem) return reply.status(501).send({ success: false, error: { code: 'NOT_IMPLEMENTED', message: 'Gallery management is unavailable' } }); return reply.send({ success: true, data: await options.settings.removeGalleryItem(params.data.clinicId, params.data.itemId, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); });
  app.get('/v1/clinic/:clinicId/closures', async (request, reply) => { const params = clinicParams.safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid clinic identifier' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; return reply.send({ success: true, data: await options.settings.listClosures(params.data.clinicId) }); });
  app.post('/v1/clinic/:clinicId/closures', async (request, reply) => { const params = clinicParams.safeParse(request.params); const body = closure.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid closure' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.status(201).send({ success: true, data: await options.settings.addClosure(params.data.clinicId, body.data, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { if (!(error instanceof ClinicSettingsError)) throw error; return reply.status(404).send({ success: false, error: { code: error.code, message: error.message } }); } });
  app.patch('/v1/clinic/:clinicId/closures/:closureId', async (request, reply) => { const params = clinicParams.extend({ closureId: postgresUuidSchema }).safeParse(request.params); const body = closureEnabled.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid closure update' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.settings.setClosureEnabled(params.data.clinicId, params.data.closureId, body.data.isEnabled, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { if (!(error instanceof ClinicSettingsError)) throw error; return reply.status(404).send({ success: false, error: { code: error.code, message: error.message } }); } });
  app.delete('/v1/clinic/:clinicId/closures/:closureId', async (request, reply) => { const params = clinicParams.extend({ closureId: postgresUuidSchema }).safeParse(request.params); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid closure' } }); const auth = await authorize(request, reply, params.data.clinicId); if (!auth) return; try { return reply.send({ success: true, data: await options.settings.removeClosure(params.data.clinicId, params.data.closureId, { id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }) }); } catch (error) { if (!(error instanceof ClinicSettingsError)) throw error; return reply.status(404).send({ success: false, error: { code: error.code, message: error.message } }); } });
}
