import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { hasClinicAccess } from '../auth/authorization.js';
import { resolveRequestAuthorization } from '../auth/request.js';
import type { AuthServices } from '../auth/types.js';
import type { CustomDomainService } from '../domains/service.js';
import { CustomDomainError } from '../domains/service.js';
import { postgresUuidSchema } from '../validation.js';
const clinic = z.object({ clinicId: postgresUuidSchema }); const domain = clinic.extend({ domainId: postgresUuidSchema }); const body = z.object({ hostname: z.string().trim().min(4).max(255) }).strict(); const actor = (auth: { user: { id: string; email: string } }) => ({ id: auth.user.id, email: auth.user.email }); const sendError = (reply: any, caught: unknown) => { if (caught instanceof CustomDomainError) return reply.status(caught.statusCode).send({ success: false, error: { code: caught.code, message: caught.message } }); throw caught; };
export async function registerCustomDomainRoutes(app: FastifyInstance, options: { auth: AuthServices; domains: CustomDomainService }) { app.get('/v1/clinic/:clinicId/custom-domains', async (request, reply) => { const p = clinic.safeParse(request.params); const auth = await resolveRequestAuthorization(request, options.auth); if (!p.success || !auth || !hasClinicAccess(auth, p.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic administrator access is required' } }); return reply.send({ success: true, data: await options.domains.list(p.data.clinicId) }); }); app.post('/v1/clinic/:clinicId/custom-domains', async (request, reply) => { const p = clinic.safeParse(request.params); const b = body.safeParse(request.body); const auth = await resolveRequestAuthorization(request, options.auth); if (!p.success || !b.success || !auth || !hasClinicAccess(auth, p.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid custom domain request' } }); try { return reply.status(201).send({ success: true, data: await options.domains.add(p.data.clinicId, b.data.hostname, actor(auth)) }); } catch (caught) { return sendError(reply, caught); } }); app.post('/v1/clinic/:clinicId/custom-domains/:domainId/verify', async (request, reply) => { const p = domain.safeParse(request.params); const auth = await resolveRequestAuthorization(request, options.auth); if (!p.success || !auth || !hasClinicAccess(auth, p.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic administrator access is required' } }); try { return reply.send({ success: true, data: await options.domains.verify(p.data.clinicId, p.data.domainId, actor(auth)) }); } catch (caught) { return sendError(reply, caught); } }); app.post('/v1/clinic/:clinicId/custom-domains/:domainId/activate', async (request, reply) => { const p = domain.safeParse(request.params); const auth = await resolveRequestAuthorization(request, options.auth); if (!p.success || !auth || !hasClinicAccess(auth, p.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic administrator access is required' } }); try { return reply.send({ success: true, data: await options.domains.activate(p.data.clinicId, p.data.domainId, actor(auth)) }); } catch (caught) { return sendError(reply, caught); } }); }
