import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { FeatureKey } from '@dentra/shared';
import { requireClinicFeature } from '../clinic/access.js';
import type { AuthServices } from '../auth/types.js';
import type { EntitlementService } from '../entitlements/service.js';
import type { CustomDomainService } from '../domains/service.js';
import { CustomDomainError } from '../domains/service.js';
import { postgresUuidSchema } from '../validation.js';
const clinic = z.object({ clinicId: postgresUuidSchema }); const domain = clinic.extend({ domainId: postgresUuidSchema }); const body = z.object({ hostname: z.string().trim().min(4).max(255) }).strict(); const actor = (auth: { user: { id: string; email: string } }) => ({ id: auth.user.id, email: auth.user.email }); const sendError = (reply: any, caught: unknown) => { if (caught instanceof CustomDomainError) return reply.status(caught.statusCode).send({ success: false, error: { code: caught.code, message: caught.message } }); throw caught; };
const adminRoles = ['clinic_owner', 'clinic_admin'] as const;
export async function registerCustomDomainRoutes(app: FastifyInstance, options: { auth: AuthServices; entitlements: EntitlementService; db?: import('@dentra/db').DB; domains: CustomDomainService }) {
  app.get('/v1/clinic/:clinicId/custom-domains', async (request, reply) => { const p = clinic.safeParse(request.params); if (!p.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid clinic identifier' } }); const auth = await requireClinicFeature(request, reply, options, p.data.clinicId, FeatureKey.CUSTOM_DOMAIN, [...adminRoles]); if (!auth) return; return reply.send({ success: true, data: await options.domains.list(p.data.clinicId) }); });
  app.post('/v1/clinic/:clinicId/custom-domains', async (request, reply) => { const p = clinic.safeParse(request.params); const b = body.safeParse(request.body); if (!p.success || !b.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid custom domain request' } }); const auth = await requireClinicFeature(request, reply, options, p.data.clinicId, FeatureKey.CUSTOM_DOMAIN, [...adminRoles]); if (!auth) return; try { return reply.status(201).send({ success: true, data: await options.domains.add(p.data.clinicId, b.data.hostname, actor(auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/clinic/:clinicId/custom-domains/:domainId/verify', async (request, reply) => { const p = domain.safeParse(request.params); if (!p.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid custom domain request' } }); const auth = await requireClinicFeature(request, reply, options, p.data.clinicId, FeatureKey.CUSTOM_DOMAIN, [...adminRoles]); if (!auth) return; try { return reply.send({ success: true, data: await options.domains.verify(p.data.clinicId, p.data.domainId, actor(auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/clinic/:clinicId/custom-domains/:domainId/activate', async (request, reply) => { const p = domain.safeParse(request.params); if (!p.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid custom domain request' } }); const auth = await requireClinicFeature(request, reply, options, p.data.clinicId, FeatureKey.CUSTOM_DOMAIN, [...adminRoles]); if (!auth) return; try { return reply.send({ success: true, data: await options.domains.activate(p.data.clinicId, p.data.domainId, actor(auth)) }); } catch (caught) { return sendError(reply, caught); } });
}
