import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { PatientPortalService } from '../patient/portal-service.js';
import { PatientPortalError } from '../patient/portal-service.js';
import { postgresUuidSchema } from '../validation.js';
const signup = z.object({ email: z.string().email().optional(), phone: z.string().trim().min(7).max(20).optional(), password: z.string().min(10).max(128) }).refine((value) => Boolean(value.email || value.phone));
const signin = z.object({ identifier: z.string().trim().min(3), password: z.string().min(10).max(128) });
const link = z.object({ clinicId: postgresUuidSchema, patientId: postgresUuidSchema, consent: z.literal(true) }).strict();
const requestBody = z.object({ clinicId: postgresUuidSchema, patientId: postgresUuidSchema, appointmentId: postgresUuidSchema.optional(), type: z.enum(['contact_update', 'appointment_cancel', 'appointment_reschedule']), payload: z.record(z.string(), z.unknown()).default({}) }).strict();
const token = (request: FastifyRequest) => request.cookies.dentra_patient_session;
function error(reply: any, caught: unknown) { if (caught instanceof PatientPortalError) return reply.status(caught.statusCode).send({ success: false, error: { code: caught.code, message: caught.message } }); throw caught; }
export async function registerPatientPortalRoutes(app: FastifyInstance, options: { portal: PatientPortalService }) { app.post('/v1/patient/auth/sign-up', async (request, reply) => { const body = signup.safeParse(request.body); if (!body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Use a valid email or mobile number and password' } }); try { return reply.status(201).send({ success: true, data: await options.portal.signUp(body.data) }); } catch (caught) { return error(reply, caught); } }); app.post('/v1/patient/auth/sign-in', async (request, reply) => { const body = signin.safeParse(request.body); if (!body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid patient credentials' } }); try { const result = await options.portal.signIn(body.data); reply.setCookie('dentra_patient_session', result.token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', path: '/', maxAge: 60 * 60 * 24 * 30 }); return reply.send({ success: true, data: { accountId: result.accountId } }); } catch (caught) { return error(reply, caught); } }); app.post('/v1/patient/auth/sign-out', async (request, reply) => { reply.clearCookie('dentra_patient_session', { path: '/' }); return reply.send({ success: true }); }); app.get('/v1/patient/portal', async (request, reply) => { try { return reply.send({ success: true, data: await options.portal.portal(token(request)) }); } catch (caught) { return error(reply, caught); } }); app.post('/v1/patient/links', async (request, reply) => { const body = link.safeParse(request.body); if (!body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Explicit clinic consent is required' } }); try { return reply.status(201).send({ success: true, data: await options.portal.link(token(request), body.data) }); } catch (caught) { return error(reply, caught); } }); app.post('/v1/patient/requests', async (request, reply) => { const body = requestBody.safeParse(request.body); if (!body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid patient request' } }); try { return reply.status(201).send({ success: true, data: await options.portal.request(token(request), body.data) }); } catch (caught) { return error(reply, caught); } }); }
