import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { hasClinicAccess, isSuperAdmin } from '../auth/authorization.js';
import { resolveRequestAuthorization } from '../auth/request.js';
import type { AuthServices } from '../auth/types.js';
import type { ReviewService } from '../reviews/service.js';
import { ReviewError } from '../reviews/service.js';
import { postgresUuidSchema } from '../validation.js';

const clinic = z.object({ clinicId: postgresUuidSchema }); const dentist = z.object({ dentistId: postgresUuidSchema }); const review = z.object({ reviewId: postgresUuidSchema });
const pagination = z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(50).default(10) });
const submit = z.object({ clinicId: postgresUuidSchema, appointmentId: postgresUuidSchema, rating: z.number().int().min(1).max(5), comment: z.string().trim().min(3).max(2000) }).strict();
const response = z.object({ response: z.string().trim().min(3).max(2000) }).strict();
const moderation = z.object({ status: z.enum(['approved', 'rejected', 'hidden']), reason: z.string().trim().min(3).max(1000) }).strict();
const moderationFilter = z.object({ status: z.enum(['all', 'pending', 'approved', 'rejected', 'hidden', 'reported']).default('pending') });
const reportBody = z.object({ reason: z.enum(['privacy', 'harassment', 'spam', 'false_information', 'other']), details: z.string().trim().max(1000).optional() }).strict();
const actor = (request: FastifyRequest, auth: { user: { id: string; email: string } }) => ({ id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] });
function sendError(reply: any, caught: unknown) { if (caught instanceof ReviewError) return reply.status(caught.statusCode).send({ success: false, error: { code: caught.code, message: caught.message } }); throw caught; }

export async function registerReviewRoutes(app: FastifyInstance, options: { auth: AuthServices; reviews: ReviewService }) {
  app.get('/v1/public/clinics/:clinicId/reviews', async (request, reply) => { const params = clinic.safeParse(request.params); const query = pagination.safeParse(request.query); if (!params.success || !query.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR' } }); return reply.send({ success: true, data: await options.reviews.listPublic(params.data.clinicId, undefined, query.data.page, query.data.pageSize) }); });
  app.get('/v1/public/dentists/:dentistId/reviews', async (request, reply) => { const params = dentist.safeParse(request.params); const query = pagination.safeParse(request.query); if (!params.success || !query.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR' } }); return reply.send({ success: true, data: await options.reviews.listPublic(undefined, params.data.dentistId, query.data.page, query.data.pageSize) }); });
  app.get('/v1/patient/reviews/eligible', async (request, reply) => { try { return reply.send({ success: true, data: await options.reviews.eligible(request.cookies.dentra_patient_session) }); } catch (caught) { return sendError(reply, caught); } });
  app.get('/v1/patient/reviews', async (request, reply) => { try { return reply.send({ success: true, data: await options.reviews.mine(request.cookies.dentra_patient_session) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/patient/reviews', { config: { rateLimit: { max: 5, timeWindow: '1 minute' } } }, async (request, reply) => { const body = submit.safeParse(request.body); if (!body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: body.error.issues[0]?.message ?? 'Invalid review' } }); try { return reply.status(201).send({ success: true, data: await options.reviews.submit(request.cookies.dentra_patient_session, body.data) }); } catch (caught) { return sendError(reply, caught); } });
  app.post('/v1/patient/reviews/:reviewId/report', { config: { rateLimit: { max: 5, timeWindow: '1 minute' } } }, async (request, reply) => { const params = review.safeParse(request.params); const body = reportBody.safeParse(request.body); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Choose a valid report reason' } }); try { return reply.status(201).send({ success: true, data: await options.reviews.report(request.cookies.dentra_patient_session, params.data.reviewId, body.data) }); } catch (caught) { return sendError(reply, caught); } });
  app.get('/v1/clinic/:clinicId/reviews', async (request, reply) => { const params = clinic.safeParse(request.params); const auth = await resolveRequestAuthorization(request, options.auth); if (!params.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR' } }); if (!auth || !hasClinicAccess(auth, params.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN' } }); return reply.send({ success: true, data: await options.reviews.listClinic(params.data.clinicId) }); });
  app.post('/v1/clinic/:clinicId/reviews/:reviewId/response', async (request, reply) => { const params = clinic.extend({ reviewId: postgresUuidSchema }).safeParse(request.params); const body = response.safeParse(request.body); const auth = await resolveRequestAuthorization(request, options.auth); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'A written response is required' } }); if (!auth || !hasClinicAccess(auth, params.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic administrator access is required' } }); try { return reply.send({ success: true, data: await options.reviews.respond(params.data.clinicId, params.data.reviewId, body.data.response, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
  app.get('/v1/admin/reviews', async (request, reply) => { const auth = await resolveRequestAuthorization(request, options.auth); const query = moderationFilter.safeParse(request.query); if (!auth || !isSuperAdmin(auth)) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Super Admin access is required' } }); if (!query.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR' } }); return reply.send({ success: true, data: await options.reviews.listModeration(query.data.status) }); });
  app.patch('/v1/admin/reviews/:reviewId', async (request, reply) => { const params = review.safeParse(request.params); const body = moderation.safeParse(request.body); const auth = await resolveRequestAuthorization(request, options.auth); if (!params.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'A written moderation reason is required' } }); if (!auth || !isSuperAdmin(auth)) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Super Admin access is required' } }); try { return reply.send({ success: true, data: await options.reviews.moderate(params.data.reviewId, body.data, actor(request, auth)) }); } catch (caught) { return sendError(reply, caught); } });
}
