import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { isSuperAdmin, getClinicAccess, hasClinicAccess } from '../auth/authorization.js';
import { resolveRequestAuthorization } from '../auth/request.js';
import type { AuthServices } from '../auth/types.js';
import type { VerificationService } from '../verification/service.js';
import { VerificationError } from '../verification/service.js';
import { postgresUuidSchema } from '../validation.js';
const clinic = z.object({ clinicId: postgresUuidSchema }); const submit = z.object({ subjectType: z.enum(['dentist', 'clinic']), documents: z.array(z.object({ type: z.string().trim().min(2).max(50), storageKey: z.string().trim().min(3).max(500) })).min(1).max(10) }).strict(); const review = z.object({ status: z.enum(['approved', 'rejected', 'revoked']), reason: z.string().trim().min(3).max(1000), expiresAt: z.string().datetime({ offset: true }).optional() }).strict(); const params = z.object({ submissionId: postgresUuidSchema }); const actor = (request: FastifyRequest, auth: { user: { id: string; email: string } }) => ({ id: auth.user.id, email: auth.user.email, ipAddress: request.ip, userAgent: request.headers['user-agent'] }); const error = (reply: any, caught: unknown) => { if (caught instanceof VerificationError) return reply.status(caught.statusCode).send({ success: false, error: { code: caught.code, message: caught.message } }); throw caught; };
export async function registerVerificationRoutes(app: FastifyInstance, options: { auth: AuthServices; verification: VerificationService }) { app.post('/v1/clinic/:clinicId/verification', async (request, reply) => { const p = clinic.safeParse(request.params); const body = submit.safeParse(request.body); if (!p.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid verification submission' } }); const auth = await resolveRequestAuthorization(request, options.auth); if (!auth || !hasClinicAccess(auth, p.data.clinicId)) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic access is required' } }); const membership = getClinicAccess(auth, p.data.clinicId).find((item) => item.role === 'dentist' && item.dentistId); if (body.data.subjectType === 'dentist' && !membership) return reply.status(403).send({ success: false, error: { code: 'DENTIST_PROFILE_REQUIRED', message: 'A linked dentist profile is required' } }); if (body.data.subjectType === 'clinic' && !hasClinicAccess(auth, p.data.clinicId, ['clinic_owner', 'clinic_admin'])) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Clinic administrator access is required' } }); try { return reply.status(201).send({ success: true, data: await options.verification.submit({ subjectType: body.data.subjectType, dentistId: body.data.subjectType === 'dentist' ? membership?.dentistId ?? undefined : undefined, clinicId: body.data.subjectType === 'clinic' ? p.data.clinicId : undefined, documents: body.data.documents, submittedBy: auth.user.id }) }); } catch (caught) { return error(reply, caught); } }); app.get('/v1/admin/verifications', async (request, reply) => { const auth = await resolveRequestAuthorization(request, options.auth); if (!auth || !isSuperAdmin(auth)) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Super Admin access is required' } }); return reply.send({ success: true, data: await options.verification.listPending() }); }); app.patch('/v1/admin/verifications/:submissionId', async (request, reply) => { const p = params.safeParse(request.params); const body = review.safeParse(request.body); const auth = await resolveRequestAuthorization(request, options.auth); if (!p.success || !body.success) return reply.status(400).send({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid verification review' } }); if (!auth || !isSuperAdmin(auth)) return reply.status(403).send({ success: false, error: { code: 'FORBIDDEN', message: 'Super Admin access is required' } }); try { return reply.send({ success: true, data: await options.verification.review(p.data.submissionId, body.data, actor(request, auth)) }); } catch (caught) { return error(reply, caught); } }); }
