import { and, avg, count, eq, inArray, isNull } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { appointments, clinicReviews, patientPortalLinks, patients } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
export type ReviewService = ReturnType<typeof createReviewService>;
export class ReviewError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
export function createReviewService(database: DB) { const currentAccount = async (token: string | undefined) => { if (!token) return null; const { createHash } = await import('node:crypto'); const hash = createHash('sha256').update(token).digest('hex'); const { patientPortalSessions } = await import('@dentra/db/schema'); const [row] = await database.select({ accountId: patientPortalSessions.accountId }).from(patientPortalSessions).where(eq(patientPortalSessions.tokenHash, hash)).limit(1); return row?.accountId ?? null; }; return {
  submit: async (token: string | undefined, input: { clinicId: string; appointmentId: string; rating: number; comment: string }) => { const accountId = await currentAccount(token); if (!accountId) throw new ReviewError('UNAUTHENTICATED', 'Patient sign-in is required', 401); const [appointment] = await database.select({ id: appointments.id, clinicId: appointments.clinicId, patientId: appointments.patientId, dentistId: appointments.dentistId, status: appointments.status }).from(appointments).where(and(eq(appointments.id, input.appointmentId), eq(appointments.clinicId, input.clinicId), eq(appointments.status, 'completed'))).limit(1); if (!appointment?.patientId) throw new ReviewError('APPOINTMENT_NOT_ELIGIBLE', 'Only completed appointments can be reviewed', 409); const [link] = await database.select({ patientId: patientPortalLinks.patientId }).from(patientPortalLinks).where(and(eq(patientPortalLinks.accountId, accountId), eq(patientPortalLinks.clinicId, input.clinicId), eq(patientPortalLinks.patientId, appointment.patientId), isNull(patientPortalLinks.revokedAt))).limit(1); if (!link) throw new ReviewError('CLINIC_NOT_LINKED', 'This clinic record is not linked to the patient account', 403); const [created] = await database.insert(clinicReviews).values({ clinicId: input.clinicId, dentistId: appointment.dentistId, appointmentId: input.appointmentId, patientId: appointment.patientId, accountId, rating: input.rating, comment: input.comment }).returning({ id: clinicReviews.id }); return created; },
  listPublic: async (clinicId: string, dentistId?: string) => { const rows = await database.select({ id: clinicReviews.id, rating: clinicReviews.rating, comment: clinicReviews.comment, response: clinicReviews.response, responseAt: clinicReviews.responseAt, createdAt: clinicReviews.createdAt }).from(clinicReviews).where(and(eq(clinicReviews.clinicId, clinicId), eq(clinicReviews.status, 'approved'), dentistId ? eq(clinicReviews.dentistId, dentistId) : undefined)); const [summary] = await database.select({ average: avg(clinicReviews.rating), total: count(clinicReviews.id) }).from(clinicReviews).where(and(eq(clinicReviews.clinicId, clinicId), eq(clinicReviews.status, 'approved'), dentistId ? eq(clinicReviews.dentistId, dentistId) : undefined)); return { reviews: rows, averageRating: Number(summary?.average ?? 0), total: Number(summary?.total ?? 0) }; },
  listPending: () => database.select({ id: clinicReviews.id, clinicId: clinicReviews.clinicId, dentistId: clinicReviews.dentistId, appointmentId: clinicReviews.appointmentId, rating: clinicReviews.rating, comment: clinicReviews.comment, status: clinicReviews.status, createdAt: clinicReviews.createdAt }).from(clinicReviews).where(eq(clinicReviews.status, 'pending')),
  moderate: async (reviewId: string, input: { status: 'approved' | 'rejected' | 'hidden'; reason: string }, actor: { id: string; email: string }) => database.transaction(async (tx) => { const [updated] = await tx.update(clinicReviews).set({ status: input.status, moderationReason: input.reason, moderatedBy: actor.id, moderatedAt: new Date(), updatedAt: new Date() }).where(eq(clinicReviews.id, reviewId)).returning({ id: clinicReviews.id, clinicId: clinicReviews.clinicId, status: clinicReviews.status }); if (!updated) throw new ReviewError('REVIEW_NOT_FOUND', 'Review not found', 404); await writeAudit(tx as unknown as DB, { actorId: actor.id, actorEmail: actor.email, clinicId: updated.clinicId, entityType: 'clinic_review', entityId: reviewId, action: AuditAction.REVIEW_MODERATED, metadata: JSON.stringify({ status: input.status, reason: input.reason }) }); return updated; }),
  respond: async (clinicId: string, reviewId: string, response: string, actor: { id: string; email: string }) => database.transaction(async (tx) => { const [updated] = await tx.update(clinicReviews).set({ response, responseAt: new Date(), updatedAt: new Date() }).where(and(eq(clinicReviews.id, reviewId), eq(clinicReviews.clinicId, clinicId), eq(clinicReviews.status, 'approved'))).returning({ id: clinicReviews.id }); if (!updated) throw new ReviewError('REVIEW_NOT_FOUND', 'Approved review not found', 404); await writeAudit(tx as unknown as DB, { actorId: actor.id, actorEmail: actor.email, clinicId, entityType: 'clinic_review', entityId: reviewId, action: AuditAction.REVIEW_RESPONDED, metadata: JSON.stringify({ responseLength: response.length }) }); return updated; }),
}; }
