"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ExternalLink, Save, ShieldCheck, Stethoscope } from "lucide-react";
import DentistScheduleEditor from "./DentistScheduleEditor";

type Profile = { id: string; firstName: string; lastName: string; slug: string; licenseNumber: string | null; specialty: string | null; bio: string | null; photoUrl: string | null; phone: string | null; email: string | null; verificationStatus: string; publicationStatus: string; affiliations: Array<{ clinicId: string; clinicName: string; branchId: string; branchName: string }> };
const editable = ["licenseNumber", "specialty", "bio", "photoUrl", "phone", "email"] as const;

export default function DentistProfileEditor() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [draft, setDraft] = useState<Profile | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const dirty = useMemo(() => profile && draft && editable.some((field) => profile[field] !== draft[field]), [profile, draft]);
  const ready = draft ? [draft.photoUrl, draft.specialty, draft.bio, draft.licenseNumber, draft.affiliations.length > 0].filter(Boolean).length : 0;

  async function load() { setError(null); const response = await fetch("/api/dentist/profile", { cache: "no-store" }); const payload = await response.json() as { data?: Profile; error?: { message?: string } }; if (!response.ok || !payload.data) { setError(payload.error?.message ?? "Unable to load professional profile"); return; } setProfile(payload.data); setDraft(payload.data); }
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => event.preventDefault(); window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);

  async function save(event: FormEvent) { event.preventDefault(); if (!draft) return; setSaving(true); setError(null); setNotice(null); const body = Object.fromEntries(editable.map((field) => [field, draft[field] || null])); const response = await fetch("/api/dentist/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { data?: Profile; error?: { message?: string } }; if (!response.ok || !payload.data) setError(payload.error?.message ?? "Unable to save profile"); else { setProfile(payload.data); setDraft(payload.data); setNotice("Professional profile saved."); } setSaving(false); }

  if (!draft) return <main className="p-6">{error ? <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-700">{error} <button onClick={() => void load()} className="font-semibold underline">Retry</button></div> : <div role="status" className="h-48 animate-pulse rounded-2xl bg-violet-100"><span className="sr-only">Loading profile</span></div>}</main>;
  const field = (name: typeof editable[number], label: string, type = "text") => <label className="text-sm font-medium text-slate-700">{label}<input type={type} value={(draft[name] as string | null) ?? ""} onChange={(event) => setDraft({ ...draft, [name]: event.target.value })} className="mt-1 h-11 w-full rounded-xl border border-slate-300 px-3 focus:border-violet-500 focus:outline-none focus:ring-2 focus:ring-violet-100" /></label>;

  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-5xl space-y-5">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-100"><Stethoscope className="text-violet-600" /></div><div><h1 className="text-2xl font-bold text-slate-900">Professional Profile</h1><p className="text-sm text-slate-500">Manage the information patients see about you.</p></div></div><Link href={`/dentists/${draft.slug}`} target="_blank" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-violet-200 px-4 text-sm font-semibold text-violet-700">Public preview <ExternalLink size={15} /></Link></header>
    {error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{notice && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{notice}</div>}
    <div className="grid gap-5 lg:grid-cols-[1fr_18rem]"><form onSubmit={save} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2">{field("specialty", "Specialty")}{field("licenseNumber", "PRC / license number")}{field("email", "Professional email", "email")}{field("phone", "Professional phone")}{field("photoUrl", "Photo URL (HTTPS)", "url")}</div><label className="block text-sm font-medium text-slate-700">Biography<textarea value={draft.bio ?? ""} onChange={(event) => setDraft({ ...draft, bio: event.target.value })} rows={7} className="mt-1 w-full rounded-xl border border-slate-300 p-3" /></label><button disabled={!dirty || saving} className="inline-flex h-11 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white disabled:opacity-40"><Save size={16} />{saving ? "Saving…" : "Save profile"}</button></form>
    <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-semibold text-slate-900"><ShieldCheck size={18} className="text-violet-600" /> Profile status</h2><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-slate-500">Slug</dt><dd className="font-medium text-slate-800">{draft.slug}</dd></div><div><dt className="text-slate-500">Verification</dt><dd className="capitalize text-slate-800">{draft.verificationStatus}</dd></div><div><dt className="text-slate-500">Publication</dt><dd className="capitalize text-slate-800">{draft.publicationStatus}</dd></div></dl><Link href="/app/settings/verification" className="mt-3 inline-flex text-xs font-semibold text-violet-700 underline">Manage verification</Link></section><section className="rounded-2xl border border-violet-100 bg-violet-50 p-5"><h2 className="font-semibold text-violet-950">Publication readiness</h2><p className="mt-1 text-sm text-violet-700">{ready}/5 profile requirements complete</p><ul className="mt-3 space-y-1 text-xs text-violet-700"><li>Photo</li><li>Specialty</li><li>Biography</li><li>License number</li><li>Active affiliation</li></ul></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Affiliations</h2>{draft.affiliations.map((item) => <p key={item.branchId} className="mt-2 text-sm text-slate-600">{item.clinicName} · {item.branchName}</p>)}{!draft.affiliations.length && <p className="mt-2 text-sm text-slate-500">No active affiliations.</p>}<p className="mt-3 text-xs text-slate-500">Contact a clinic administrator to request changes.</p></section></aside></div>
    <DentistScheduleEditor affiliations={draft.affiliations} />
  </div></main>;
}
