import { index, integer, pgTable, text, uuid, varchar } from 'drizzle-orm/pg-core';
import { branches } from './branches';
import { clinics } from './clinics';
import { encounters } from './encounters';
import { patients } from './patients';
import { id, timestamps } from './helpers';

// ---------------------------------------------------------------------------
// clinical_files — private clinical attachments (X-rays, photos, documents).
//
// Files are stored in Replit Object Storage (private) and served via
// short-lived signed tokens generated by the API. Direct public access
// is never allowed.
//
// TENANT SCOPED: every query must filter by clinic_id.
// ---------------------------------------------------------------------------

export const clinicalFiles = pgTable(
  'clinical_files',
  {
    id: id(),

    /** Tenant scope */
    clinicId: uuid('clinic_id')
      .notNull()
      .references(() => clinics.id, { onDelete: 'restrict' }),
    branchId: uuid('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'restrict' }),
    patientId: uuid('patient_id')
      .notNull()
      .references(() => patients.id, { onDelete: 'restrict' }),

    /** Source encounter — nullable (file may be uploaded outside an encounter) */
    encounterId: uuid('encounter_id')
      .references(() => encounters.id, { onDelete: 'set null' }),

    /**
     * Clinical category of this file.
     * Values: 'radiograph' | 'intraoral_photo' | 'extraoral_photo' |
     *         'consent_form' | 'lab_result' | 'referral_letter' | 'other'
     */
    fileType: varchar('file_type', { length: 50 }).notNull(),

    /**
     * Object Storage key used to retrieve/delete the file.
     * Format: clinical/{clinicId}/{fileId}
     */
    storageKey: varchar('storage_key', { length: 500 }).notNull(),

    /** Original filename as uploaded by the user */
    originalFilename: varchar('original_filename', { length: 300 }).notNull(),

    /** MIME type validated at upload time */
    mimeType: varchar('mime_type', { length: 100 }).notNull(),

    /** File size in bytes — validated ≤ 20 MB at upload */
    sizeBytes: integer('size_bytes').notNull(),

    /**
     * Optional FDI tooth reference (e.g. "16", "36") if the file is specific
     * to a single tooth. Null for full-arch or non-tooth files.
     */
    toothRef: varchar('tooth_ref', { length: 50 }),

    /** Free-text annotation for this file */
    notes: text('notes'),

    /** User ID of the staff member who uploaded the file */
    uploadedBy: uuid('uploaded_by'),

    ...timestamps,
  },
  (t) => ({
    clinicIdx:    index('clinical_files_clinic_id_idx').on(t.clinicId),
    patientIdx:   index('clinical_files_patient_id_idx').on(t.patientId),
    encounterIdx: index('clinical_files_encounter_id_idx').on(t.encounterId),
    typeIdx:      index('clinical_files_file_type_idx').on(t.clinicId, t.fileType),
  }),
);

export type ClinicalFile    = typeof clinicalFiles.$inferSelect;
export type NewClinicalFile = typeof clinicalFiles.$inferInsert;
