import { index, numeric, pgEnum, pgTable, text, timestamp, unique, uuid, varchar } from 'drizzle-orm/pg-core';
import { clinics } from './clinics';
import { invoices } from './billing';
import { id, timestamps } from './helpers';
export const paymentLinkStatusEnum = pgEnum('payment_link_status', ['active', 'paid', 'expired', 'cancelled']);
export const onlinePaymentStatusEnum = pgEnum('online_payment_status', ['pending', 'succeeded', 'failed', 'refunded']);
export const paymentLinks = pgTable('payment_links', { id: id(), clinicId: uuid('clinic_id').notNull().references(() => clinics.id, { onDelete: 'cascade' }), invoiceId: uuid('invoice_id').notNull().references(() => invoices.id, { onDelete: 'restrict' }), tokenHash: varchar('token_hash', { length: 128 }).notNull(), amountPhp: numeric('amount_php', { precision: 10, scale: 2 }).notNull(), status: paymentLinkStatusEnum('status').notNull().default('active'), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), ...timestamps }, (t) => ({ tokenUnique: unique('payment_link_token_unique').on(t.tokenHash), clinicIdx: index('payment_links_clinic_idx').on(t.clinicId), invoiceIdx: index('payment_links_invoice_idx').on(t.invoiceId) }));
export const onlinePayments = pgTable('online_payments', { id: id(), clinicId: uuid('clinic_id').notNull().references(() => clinics.id, { onDelete: 'cascade' }), invoiceId: uuid('invoice_id').notNull().references(() => invoices.id, { onDelete: 'restrict' }), linkId: uuid('link_id').notNull().references(() => paymentLinks.id, { onDelete: 'restrict' }), provider: varchar('provider', { length: 50 }).notNull(), providerPaymentId: varchar('provider_payment_id', { length: 200 }).notNull(), amountPhp: numeric('amount_php', { precision: 10, scale: 2 }).notNull(), status: onlinePaymentStatusEnum('status').notNull(), failureReason: text('failure_reason'), paidAt: timestamp('paid_at', { withTimezone: true }), ...timestamps }, (t) => ({ providerPaymentUnique: unique('online_payment_provider_unique').on(t.provider, t.providerPaymentId), invoiceIdx: index('online_payments_invoice_idx').on(t.clinicId, t.invoiceId) }));
export const paymentWebhookEvents = pgTable('payment_webhook_events', { id: id(), provider: varchar('provider', { length: 50 }).notNull(), eventId: varchar('event_id', { length: 200 }).notNull(), eventType: varchar('event_type', { length: 100 }).notNull(), payload: text('payload').notNull(), receivedAt: timestamp('received_at', { withTimezone: true }).notNull(), ...timestamps }, (t) => ({ eventUnique: unique('payment_webhook_event_unique').on(t.provider, t.eventId) }));
