'use client';
import { useState } from 'react';
import { Loader2, Plus } from 'lucide-react';
import type { ClinicServiceOption, TreatmentRecord } from '@/lib/clinic-treatments';

const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(value)) : 'Not recorded';
export default function TreatmentPanel({ clinicId, encounterId, isFinal, services, treatments }: { clinicId: string; encounterId: string; isFinal: boolean; services: ClinicServiceOption[]; treatments: TreatmentRecord[] }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); const payload = { serviceId: String(form.get('serviceId') ?? ''), toothRef: String(form.get('toothRef') ?? '').trim() || undefined, notes: String(form.get('notes') ?? '').trim() || undefined, performedAt: String(form.get('performedAt') ?? '') ? new Date(String(form.get('performedAt'))).toISOString() : undefined }; try { const response = await fetch(`/api/clinic/encounters/${encodeURIComponent(encounterId)}/treatments?clinicId=${encodeURIComponent(clinicId)}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(result.error?.message ?? 'Treatment could not be recorded'); window.location.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Treatment could not be recorded'); setSaving(false); } }
  const field = 'mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm';
  return <section className="mt-7 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold text-slate-900">Treatment records</h2><p className="mt-1 text-sm text-slate-500">Completed procedures linked to this encounter.</p>{treatments.length ? <div className="mt-5 divide-y divide-slate-100">{treatments.map((item) => <article key={item.id} className="grid gap-2 py-4 text-sm sm:grid-cols-4"><div><p className="font-bold text-slate-900">{item.serviceName ?? 'Dental procedure'}</p><p className="text-xs text-slate-500">{dateTime(item.performedAt)}</p></div><p className="text-slate-600">Tooth/area: {item.toothRef ?? 'General'}</p><p className="text-slate-600">{item.dentistFirstName ? `Dr. ${item.dentistFirstName} ${item.dentistLastName}` : 'Dentist'}</p><p className="text-slate-600">{item.notes ?? 'No notes'}</p></article>)}</div> : <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No treatment records yet.</p>}{!isFinal && <form onSubmit={submit} className="mt-6 grid gap-4 border-t border-slate-100 pt-6 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Procedure/service<select required name="serviceId" className={field}><option value="">Select service</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Tooth or area<input name="toothRef" maxLength={50} placeholder="e.g. 16 or upper-left quadrant" className={field} /></label><label className="text-sm font-semibold text-slate-700">Performed at<input name="performedAt" type="datetime-local" className={field} /></label><label className="text-sm font-semibold text-slate-700">Notes<textarea name="notes" rows={2} maxLength={5000} className={field} /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}<button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white sm:col-span-2 sm:justify-self-start">{saving ? <Loader2 className="animate-spin" size={17} /> : <Plus size={17} />}Add treatment record</button></form>}{isFinal && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">This encounter is finalized; its treatment records are read-only.</p>}</section>;
}
