import { createHash, randomBytes, scrypt as nodeScrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { and, eq, inArray, isNull, gte } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { appointments, clinics, invoices, patientAccounts, patientPortalLinks, patientPortalRequests, patientPortalSessions, patients, services, treatmentPlans } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
const scrypt = promisify(nodeScrypt);
export class PatientPortalError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
export type PatientPortalService = ReturnType<typeof createPatientPortalService>;
const tokenHash = (token: string) => createHash('sha256').update(token).digest('hex');
async function passwordHash(password: string) { const salt = randomBytes(16).toString('hex'); const derived = await scrypt(password, salt, 64) as Buffer; return `${salt}:${derived.toString('hex')}`; }
async function passwordMatches(password: string, stored: string) { const [salt, hex] = stored.split(':'); if (!salt || !hex) return false; const derived = await scrypt(password, salt, 64) as Buffer; const expected = Buffer.from(hex, 'hex'); return expected.length === derived.length && timingSafeEqual(expected, derived); }
export function createPatientPortalService(database: DB) {
  const session = async (token: string | undefined) => { if (!token) return null; const [row] = await database.select({ accountId: patientPortalSessions.accountId, email: patientAccounts.email, phone: patientAccounts.phone }).from(patientPortalSessions).innerJoin(patientAccounts, eq(patientPortalSessions.accountId, patientAccounts.id)).where(and(eq(patientPortalSessions.tokenHash, tokenHash(token)), gte(patientPortalSessions.expiresAt, new Date()), eq(patientAccounts.status, 'active'))).limit(1); return row ?? null; };
  const linkPatient = async (token: string | undefined, input: { clinicId: string; patientId: string; consent: boolean }) => {
    const current = await session(token);
    if (!current || !input.consent) throw new PatientPortalError('CONSENT_REQUIRED', 'Explicit consent is required to link this clinic record', 403);
    const [patient] = await database.select({ id: patients.id, clinicId: patients.clinicId, email: patients.email, phone: patients.phone }).from(patients).where(and(eq(patients.id, input.patientId), eq(patients.clinicId, input.clinicId), isNull(patients.deletedAt))).limit(1);
    const emailMatches = Boolean(current.email && patient?.email && patient.email.toLowerCase() === current.email.toLowerCase());
    const phoneMatches = Boolean(current.phone && patient?.phone && patient.phone === current.phone);
    if (!patient || (!emailMatches && !phoneMatches)) throw new PatientPortalError('LINK_NOT_VERIFIED', 'The account contact does not match this clinic record', 403);
    const [linked] = await database.insert(patientPortalLinks).values({ accountId: current.accountId, clinicId: input.clinicId, patientId: input.patientId, consentedAt: new Date() }).onConflictDoUpdate({ target: [patientPortalLinks.accountId, patientPortalLinks.patientId], set: { clinicId: input.clinicId, consentedAt: new Date(), revokedAt: null } }).returning({ id: patientPortalLinks.id });
    return linked;
  };
  return {
    signUp: async (input: { email?: string; phone?: string; password: string }) => { if (!input.email && !input.phone) throw new PatientPortalError('CONTACT_REQUIRED', 'Email or mobile number is required'); const email = input.email?.trim().toLowerCase(); const phone = input.phone?.trim(); const existing = await database.select({ id: patientAccounts.id }).from(patientAccounts).where(email ? eq(patientAccounts.email, email) : eq(patientAccounts.phone, phone!)).limit(1); if (existing.length) throw new PatientPortalError('ACCOUNT_EXISTS', 'A patient account already exists', 409); const [account] = await database.insert(patientAccounts).values({ email: email ?? null, phone: phone ?? null, passwordHash: await passwordHash(input.password) }).returning({ id: patientAccounts.id }); return account; },
    signIn: async (input: { identifier: string; password: string }) => { const identifier = input.identifier.trim(); const [account] = await database.select({ id: patientAccounts.id, email: patientAccounts.email, phone: patientAccounts.phone, passwordHash: patientAccounts.passwordHash }).from(patientAccounts).where(and(identifier.includes('@') ? eq(patientAccounts.email, identifier.toLowerCase()) : eq(patientAccounts.phone, identifier), eq(patientAccounts.status, 'active'))).limit(1); if (!account || !(await passwordMatches(input.password, account.passwordHash))) throw new PatientPortalError('INVALID_CREDENTIALS', 'Invalid patient account credentials', 401); const token = randomBytes(32).toString('base64url'); await database.insert(patientPortalSessions).values({ accountId: account.id, tokenHash: tokenHash(token), expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30) }); return { token, accountId: account.id }; },
    signOut: async (token: string | undefined) => { if (token) await database.delete(patientPortalSessions).where(eq(patientPortalSessions.tokenHash, tokenHash(token))); },
    getSession: session,
    link: linkPatient,
    linkByReference: async (token: string | undefined, input: { clinicSlug: string; patientNumber: string; consent: boolean }) => { const [record] = await database.select({ clinicId: patients.clinicId, patientId: patients.id }).from(patients).innerJoin(clinics, eq(patients.clinicId, clinics.id)).where(and(eq(clinics.slug, input.clinicSlug.trim().toLowerCase()), eq(patients.patientNumber, input.patientNumber.trim()), isNull(patients.deletedAt))).limit(1); if (!record) throw new PatientPortalError('LINK_NOT_VERIFIED', 'No matching clinic record was found', 403); return linkPatient(token, { ...record, consent: input.consent }); },
    revokeLink: async (token: string | undefined, clinicId: string, patientId: string) => { const current = await session(token); if (!current) throw new PatientPortalError('UNAUTHENTICATED', 'Patient sign-in is required', 401); const [revoked] = await database.update(patientPortalLinks).set({ revokedAt: new Date(), updatedAt: new Date() }).where(and(eq(patientPortalLinks.accountId, current.accountId), eq(patientPortalLinks.clinicId, clinicId), eq(patientPortalLinks.patientId, patientId), isNull(patientPortalLinks.revokedAt))).returning({ id: patientPortalLinks.id }); if (!revoked) throw new PatientPortalError('LINK_NOT_FOUND', 'Linked clinic record was not found', 404); return revoked; },
    portal: async (token: string | undefined) => { const current = await session(token); if (!current) throw new PatientPortalError('UNAUTHENTICATED', 'Patient sign-in is required', 401); const links = await database.select({ clinicId: patientPortalLinks.clinicId, patientId: patientPortalLinks.patientId, clinicName: clinics.name, patientFirstName: patients.firstName, patientLastName: patients.lastName }).from(patientPortalLinks).innerJoin(clinics, eq(patientPortalLinks.clinicId, clinics.id)).innerJoin(patients, and(eq(patientPortalLinks.patientId, patients.id), eq(patients.clinicId, patientPortalLinks.clinicId))).where(and(eq(patientPortalLinks.accountId, current.accountId), isNull(patientPortalLinks.revokedAt))); const patientIds = links.map((link) => link.patientId); if (!patientIds.length) return { account: { email: current.email, phone: current.phone }, links, appointments: [], invoices: [], treatmentPlans: [], requests: [] }; const [appointmentRows, invoiceRows, planRows, requestRows] = await Promise.all([database.select({ id: appointments.id, clinicId: appointments.clinicId, patientId: appointments.patientId, clinicName: clinics.name, serviceName: services.name, status: appointments.status, startsAt: appointments.startsAt, endsAt: appointments.endsAt }).from(appointments).innerJoin(clinics, eq(appointments.clinicId, clinics.id)).leftJoin(services, eq(appointments.serviceId, services.id)).where(inArray(appointments.patientId, patientIds)), database.select({ id: invoices.id, clinicId: invoices.clinicId, patientId: invoices.patientId, invoiceNumber: invoices.invoiceNumber, status: invoices.status, totalAmountPhp: invoices.totalAmountPhp, issuedAt: invoices.issuedAt }).from(invoices).where(inArray(invoices.patientId, patientIds)), database.select({ id: treatmentPlans.id, clinicId: treatmentPlans.clinicId, patientId: treatmentPlans.patientId, title: treatmentPlans.title, status: treatmentPlans.status, createdAt: treatmentPlans.createdAt }).from(treatmentPlans).where(inArray(treatmentPlans.patientId, patientIds)), database.select({ id: patientPortalRequests.id, clinicId: patientPortalRequests.clinicId, type: patientPortalRequests.type, status: patientPortalRequests.status, createdAt: patientPortalRequests.createdAt }).from(patientPortalRequests).where(eq(patientPortalRequests.accountId, current.accountId))]); return { account: { email: current.email, phone: current.phone }, links, appointments: appointmentRows, invoices: invoiceRows, treatmentPlans: planRows, requests: requestRows }; },
    request: async (token: string | undefined, input: { clinicId: string; patientId: string; type: 'contact_update' | 'appointment_cancel' | 'appointment_reschedule'; appointmentId?: string; payload: Record<string, unknown> }) => { const current = await session(token); if (!current) throw new PatientPortalError('UNAUTHENTICATED', 'Patient sign-in is required', 401); const [link] = await database.select({ id: patientPortalLinks.id }).from(patientPortalLinks).where(and(eq(patientPortalLinks.accountId, current.accountId), eq(patientPortalLinks.clinicId, input.clinicId), eq(patientPortalLinks.patientId, input.patientId), isNull(patientPortalLinks.revokedAt))).limit(1); if (!link) throw new PatientPortalError('CLINIC_NOT_LINKED', 'This clinic record has not been explicitly linked', 403); if (input.appointmentId) { const [appointment] = await database.select({ id: appointments.id }).from(appointments).where(and(eq(appointments.id, input.appointmentId), eq(appointments.clinicId, input.clinicId), eq(appointments.patientId, input.patientId))).limit(1); if (!appointment) throw new PatientPortalError('APPOINTMENT_NOT_FOUND', 'Appointment is not part of this linked clinic record', 404); } const [created] = await database.insert(patientPortalRequests).values({ accountId: current.accountId, clinicId: input.clinicId, patientId: input.patientId, appointmentId: input.appointmentId ?? null, type: input.type, payload: JSON.stringify(input.payload) }).returning({ id: patientPortalRequests.id }); return created; },
  };
}
