import { and, asc, eq, gte, lt } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { appointments, appointmentStatusHistory, branches, dentists, patients, services } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction, FeatureKey } from '@dentra/shared';
import type { EntitlementService } from '../entitlements/service.js';
import type { IntegrationService } from '../integrations/service.js';

export type KioskLookup = { patientNumber?: string; lastName?: string; dateOfBirth?: string };
export class KioskError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
export type KioskService = ReturnType<typeof createKioskService>;
function dayRange(date: string) { const start = new Date(`${date}T00:00:00+08:00`); return { start, end: new Date(start.getTime() + 86_400_000) }; }
function manilaToday() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
function match(input: KioskLookup) { return input.patientNumber ? eq(patients.patientNumber, input.patientNumber.trim()) : and(eq(patients.lastName, input.lastName!.trim()), eq(patients.dateOfBirth, input.dateOfBirth!.trim())); }
export function createKioskService(database: DB, entitlements: EntitlementService, integrations?: IntegrationService) {
  async function clinicForBranch(branchId: string) { const [branch] = await database.select({ id: branches.id, clinicId: branches.clinicId, name: branches.name }).from(branches).where(and(eq(branches.id, branchId), eq(branches.isActive, true))).limit(1); if (!branch) throw new KioskError('BRANCH_NOT_FOUND', 'Active branch not found', 404); const entitlement = await entitlements.resolve(branch.clinicId); if (!entitlement) throw new KioskError('CLINIC_NOT_FOUND', 'Clinic not found', 404); if (!entitlement.entitlements.some((item) => item.featureKey === FeatureKey.KIOSK_CHECKIN && item.isEnabled)) throw new KioskError('ENTITLEMENT_REQUIRED', 'Kiosk check-in is not enabled for this clinic', 403); return branch; }
  const select = { id: appointments.id, branchId: appointments.branchId, startsAt: appointments.startsAt, endsAt: appointments.endsAt, status: appointments.status, patientFirstName: patients.firstName, patientLastName: patients.lastName, patientNumber: patients.patientNumber, dentistFirstName: dentists.firstName, dentistLastName: dentists.lastName, serviceName: services.name };
  return {
    lookup: async (branchId: string, input: KioskLookup) => { const branch = await clinicForBranch(branchId); const { start, end } = dayRange(manilaToday()); const rows = await database.select(select).from(appointments).innerJoin(patients, and(eq(appointments.patientId, patients.id), eq(patients.clinicId, branch.clinicId))).leftJoin(dentists, eq(appointments.dentistId, dentists.id)).leftJoin(services, and(eq(appointments.serviceId, services.id), eq(services.clinicId, branch.clinicId))).where(and(eq(appointments.clinicId, branch.clinicId), eq(appointments.branchId, branchId), gte(appointments.startsAt, start), lt(appointments.startsAt, end), match(input))).orderBy(asc(appointments.startsAt)).limit(5); return { branch: { id: branch.id, name: branch.name }, appointments: rows.map((row) => ({ id: row.id, startsAt: row.startsAt, endsAt: row.endsAt, status: row.status, patientFirstName: row.patientFirstName, patientLastInitial: `${row.patientLastName[0] ?? ''}.`, patientNumber: row.patientNumber, dentistName: row.dentistFirstName && row.dentistLastName ? `Dr. ${row.dentistFirstName} ${row.dentistLastName}` : null, serviceName: row.serviceName })) }; },
    checkIn: async (branchId: string, appointmentId: string, input: KioskLookup) => { const branch = await clinicForBranch(branchId); const { start, end } = dayRange(manilaToday()); const result = await database.transaction(async (tx) => { const [row] = await tx.select(select).from(appointments).innerJoin(patients, and(eq(appointments.patientId, patients.id), eq(patients.clinicId, branch.clinicId))).where(and(eq(appointments.id, appointmentId), eq(appointments.clinicId, branch.clinicId), eq(appointments.branchId, branchId), gte(appointments.startsAt, start), lt(appointments.startsAt, end), match(input))).limit(1).for('update'); if (!row) throw new KioskError('APPOINTMENT_NOT_FOUND', 'Appointment not found for today at this branch', 404); if (!['pending', 'confirmed'].includes(row.status)) throw new KioskError('INVALID_STATUS', 'This appointment is no longer eligible for kiosk check-in', 409); const [updated] = await tx.update(appointments).set({ status: 'checked_in', checkedInAt: new Date() }).where(and(eq(appointments.id, appointmentId), eq(appointments.status, row.status))).returning({ id: appointments.id, status: appointments.status, startsAt: appointments.startsAt }); if (!updated) throw new KioskError('APPOINTMENT_CONFLICT', 'Appointment changed before check-in', 409); await tx.insert(appointmentStatusHistory).values({ appointmentId, clinicId: branch.clinicId, fromStatus: row.status, toStatus: 'checked_in', changedBy: null, reason: 'kiosk_check_in' }); await writeAudit(tx, { actorId: null, actorEmail: null, clinicId: branch.clinicId, entityType: 'appointment', entityId: appointmentId, action: AuditAction.APPOINTMENT_STATUS_CHANGED, metadata: JSON.stringify({ fromStatus: row.status, toStatus: 'checked_in', source: 'kiosk' }) }); return { updated, fromStatus: row.status }; }); integrations?.dispatchEvent(branch.clinicId, 'appointment.updated', { appointmentId, fromStatus: result.fromStatus, toStatus: result.updated.status }); return result.updated; },
  };
}
