import { and, desc, eq } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { clinics, dentists, verificationSubmissions } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
export type VerificationActor = { id: string; email: string; ipAddress?: string; userAgent?: string };
export type VerificationService = ReturnType<typeof createVerificationService>;
export class VerificationError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
export function createVerificationService(database: DB) { return {
  submit: async (input: { subjectType: 'dentist' | 'clinic'; dentistId?: string; clinicId?: string; documents: Array<{ type: string; storageKey: string }>; submittedBy: string }) => { if (input.subjectType === 'dentist' && !input.dentistId || input.subjectType === 'clinic' && !input.clinicId) throw new VerificationError('SUBJECT_REQUIRED', 'A verification subject is required'); const [created] = await database.insert(verificationSubmissions).values({ subjectType: input.subjectType, dentistId: input.dentistId ?? null, clinicId: input.clinicId ?? null, documents: JSON.stringify(input.documents), submittedBy: input.submittedBy }).returning({ id: verificationSubmissions.id }); if (input.dentistId) await database.update(dentists).set({ verificationStatus: 'pending' }).where(eq(dentists.id, input.dentistId)); if (input.clinicId) await database.update(clinics).set({ verificationStatus: 'pending' }).where(eq(clinics.id, input.clinicId)); return created; },
  listPending: () => database.select({ id: verificationSubmissions.id, subjectType: verificationSubmissions.subjectType, dentistId: verificationSubmissions.dentistId, clinicId: verificationSubmissions.clinicId, documents: verificationSubmissions.documents, status: verificationSubmissions.status, submittedBy: verificationSubmissions.submittedBy, createdAt: verificationSubmissions.createdAt }).from(verificationSubmissions).where(eq(verificationSubmissions.status, 'pending')).orderBy(desc(verificationSubmissions.createdAt)),
  review: async (submissionId: string, input: { status: 'approved' | 'rejected' | 'revoked'; reason: string; expiresAt?: string }, actor: VerificationActor) => database.transaction(async (tx) => { const [submission] = await tx.select().from(verificationSubmissions).where(eq(verificationSubmissions.id, submissionId)).limit(1).for('update'); if (!submission) throw new VerificationError('SUBMISSION_NOT_FOUND', 'Verification submission not found', 404); const [updated] = await tx.update(verificationSubmissions).set({ status: input.status, reviewReason: input.reason, reviewedBy: actor.id, reviewedAt: new Date(), expiresAt: input.expiresAt ? new Date(input.expiresAt) : null, updatedAt: new Date() }).where(eq(verificationSubmissions.id, submissionId)).returning(); if (submission.dentistId) await tx.update(dentists).set({ verificationStatus: input.status === 'approved' ? 'verified' : 'unverified' }).where(eq(dentists.id, submission.dentistId)); if (submission.clinicId) await tx.update(clinics).set({ verificationStatus: input.status === 'approved' ? 'verified' : 'unverified' }).where(eq(clinics.id, submission.clinicId)); await writeAudit(tx as unknown as DB, { actorId: actor.id, actorEmail: actor.email, clinicId: submission.clinicId, entityType: 'verification_submission', entityId: submissionId, action: input.status === 'approved' ? AuditAction.VERIFICATION_APPROVED : input.status === 'revoked' ? AuditAction.VERIFICATION_REVOKED : AuditAction.VERIFICATION_REJECTED, metadata: JSON.stringify({ subjectType: submission.subjectType, reason: input.reason }), ipAddress: actor.ipAddress, userAgent: actor.userAgent }); return updated; }),
}; }
