'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Download, Loader2, RefreshCw } from 'lucide-react';

type Branch = { id: string; name: string };
type AppointmentTrend = { day: string; status: string; total: number };
type RevenueTrend = { day: string; revenuePhp: string };
type Analytics = { trends: { appointments: AppointmentTrend[]; revenue: RevenueTrend[] }; conversionRate: number; noShowRate: number; cancellationRate: number; treatmentAcceptanceRate: number | null; revenueVisible: boolean };
const manilaDate = (value: Date) => { const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(value); const get = (type: string) => parts.find((item) => item.type === type)?.value; return `${get('year')}-${get('month')}-${get('day')}`; };
const statusLabel = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function AnalyticsClient({ clinicId, branches, revenueVisible }: { clinicId: string; branches: Branch[]; revenueVisible: boolean }) {
  const today = manilaDate(new Date()); const initialFrom = manilaDate(new Date(Date.now() - 29 * 86_400_000));
  const [filters, setFilters] = useState({ from: initialFrom, to: today, branchId: '' }); const [applied, setApplied] = useState(filters);
  const [data, setData] = useState<Analytics | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const query = useMemo(() => new URLSearchParams(Object.entries(applied).filter(([, value]) => value)).toString(), [applied]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/clinic/${clinicId}/analytics?${query}`, { cache: 'no-store' }); const body = await response.json() as { success: boolean; data?: Analytics; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? 'Unable to load analytics'); setData(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load analytics'); } finally { setLoading(false); } }, [clinicId, query]);
  useEffect(() => { void load(); }, [load]);
  function apply(event: FormEvent) { event.preventDefault(); if (filters.from > filters.to) { setError('Start date must be on or before end date.'); return; } setApplied(filters); }
  function preset(days: number) { const next = { ...filters, from: manilaDate(new Date(Date.now() - (days - 1) * 86_400_000)), to: today }; setFilters(next); setApplied(next); }
  const days = useMemo(() => { const map = new Map<string, Record<string, number>>(); for (const row of data?.trends.appointments ?? []) { const current = map.get(row.day) ?? {}; current[row.status] = Number(row.total); map.set(row.day, current); } return Array.from(map.entries()).map(([day, statuses]) => ({ day, statuses, total: Object.values(statuses).reduce((sum, value) => sum + value, 0) })); }, [data]);
  const maxAppointments = Math.max(1, ...days.map((day) => day.total)); const maxRevenue = Math.max(1, ...(data?.trends.revenue.map((row) => Number(row.revenuePhp)) ?? []));
  const hasData = Boolean(days.length || data?.trends.revenue.length);
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8"><header><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><BarChart3 className="text-violet-600" /> Advanced analytics</h1><p className="mt-1 text-sm text-slate-500">Aggregate Manila-time trends only—no patient names or clinical notes are included.</p></header>
    <form onSubmit={apply} className="rounded-2xl border border-violet-100 bg-white p-4"><div className="mb-3 flex flex-wrap gap-2">{[7, 30, 90].map((days) => <button key={days} type="button" onClick={() => preset(days)} className="rounded-lg bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700">Last {days} days</button>)}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold text-slate-600">From<input required type="date" value={filters.from} onChange={(event) => setFilters({ ...filters, from: event.target.value })} className="mt-1 h-11 w-full rounded-xl border border-violet-200 px-3" /></label><label className="text-xs font-semibold text-slate-600">To<input required type="date" value={filters.to} onChange={(event) => setFilters({ ...filters, to: event.target.value })} className="mt-1 h-11 w-full rounded-xl border border-violet-200 px-3" /></label><label className="text-xs font-semibold text-slate-600">Branch<select value={filters.branchId} onChange={(event) => setFilters({ ...filters, branchId: event.target.value })} className="mt-1 h-11 w-full rounded-xl border border-violet-200 px-3"><option value="">All assigned branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><button className="mt-auto h-11 rounded-xl bg-violet-600 px-4 text-sm font-semibold text-white hover:bg-violet-700">Apply filters</button></div></form>
    {error && <div role="alert" className="flex items-center justify-between rounded-xl bg-red-50 p-4 text-sm text-red-700"><span>{error}</span><button onClick={() => void load()} className="inline-flex items-center gap-1 font-semibold"><RefreshCw size={14} /> Retry</button></div>}{loading ? <div role="status" className="flex justify-center py-16"><Loader2 className="animate-spin text-violet-600" /><span className="sr-only">Loading analytics</span></div> : data && <>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric title="Appointment conversion" value={data.conversionRate} definition="Completed appointments divided by all appointment records in the selected date and branch scope." /><Metric title="No-show rate" value={data.noShowRate} definition="No-show appointments divided by all appointment records in the selected scope." /><Metric title="Cancellation rate" value={data.cancellationRate} definition="Cancelled appointments divided by all appointment records in the selected scope." /><Metric title="Treatment acceptance" value={data.treatmentAcceptanceRate} definition={data.treatmentAcceptanceRate === null ? 'Unavailable for a branch-only scope because treatment plans are currently clinic-owned.' : 'Accepted, scheduled, active, or completed plan items divided by all proposed clinic items in the date range.'} /></section>
      {!hasData && <div className="rounded-2xl border border-dashed border-violet-200 bg-white p-10 text-center text-sm text-slate-500">No analytics activity matches this date and branch scope.</div>}
      {days.length > 0 && <ChartSection title="Appointment trend"><div className="flex h-56 items-end gap-2 overflow-x-auto border-b border-l border-slate-200 px-3 pt-4" role="img" aria-label="Daily appointment volume bar chart">{days.map((day) => <div key={day.day} className="flex h-full min-w-10 flex-1 flex-col justify-end"><div title={`${day.day}: ${day.total} appointments`} className="w-full rounded-t bg-violet-600" style={{ height: `${Math.max(4, day.total / maxAppointments * 100)}%` }} /><span className="mt-2 -rotate-45 whitespace-nowrap text-[9px] text-slate-500">{day.day.slice(5)}</span></div>)}</div><AnalyticsTable headers={['Day', 'Total', 'Status breakdown']} rows={days.map((day) => [day.day, day.total, Object.entries(day.statuses).map(([status, total]) => `${statusLabel(status)}: ${total}`).join(' · ')])} /></ChartSection>}
      {revenueVisible && data.revenueVisible && data.trends.revenue.length > 0 && <ChartSection title="Invoiced revenue trend"><div className="space-y-2" role="img" aria-label="Daily invoiced revenue bar chart">{data.trends.revenue.map((row) => <div key={row.day} className="grid grid-cols-[5rem_1fr_auto] items-center gap-2 text-xs"><span className="text-slate-500">{row.day.slice(5)}</span><div className="h-5 rounded bg-violet-50"><div className="h-5 rounded bg-violet-500" style={{ width: `${Math.max(2, Number(row.revenuePhp) / maxRevenue * 100)}%` }} /></div><span className="font-semibold text-slate-700">₱{Number(row.revenuePhp).toLocaleString('en-PH')}</span></div>)}</div><AnalyticsTable headers={['Day', 'Invoiced revenue']} rows={data.trends.revenue.map((row) => [row.day, `₱${Number(row.revenuePhp).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`])} /></ChartSection>}
      <a href={`/api/clinic/${clinicId}/analytics?${query}&format=csv`} className="inline-flex items-center gap-2 rounded-xl border border-violet-200 bg-white px-4 py-2.5 text-sm font-semibold text-violet-700 hover:bg-violet-50"><Download size={16} /> Export aggregate CSV</a>
    </>}
  </main>;
}
function Metric({ title, value, definition }: { title: string; value: number | null; definition: string }) { return <article className="rounded-2xl border border-violet-100 bg-white p-5"><p className="text-sm font-semibold text-violet-800">{title}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value === null ? '—' : `${(value * 100).toFixed(1)}%`}</p><p className="mt-2 text-xs leading-5 text-slate-500">{definition}</p></article>; }
function ChartSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-5 rounded-2xl border border-violet-100 bg-white p-5"><h2 className="font-bold text-slate-900">{title}</h2>{children}</section>; }
function AnalyticsTable({ headers, rows }: { headers: string[]; rows: Array<Array<string | number>> }) { return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-3 py-2">{header}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={String(row[0])}>{row.map((cell, index) => <td key={index} className="px-3 py-2 text-slate-700">{cell}</td>)}</tr>)}</tbody></table></div>; }
