import { afterEach, describe, expect, it, vi } from 'vitest'; import type { FastifyInstance } from 'fastify'; import { buildApp } from '../src/app.js'; import type { ClinicSettingsService } from '../src/clinic/settings-service.js'; import type { AdminClinicSettingsService } from '../src/admin/clinic-settings-service.js'; import type { AuthServices, AuthorizationContext } from '../src/auth/types.js'; import type { ApiConfig } from '../src/config.js';
const config: ApiConfig = { nodeEnv: 'test', host: '127.0.0.1', port: 3001, logLevel: 'silent', corsOrigins: [], authSecret: 'test-secret-that-is-at-least-32-characters', authBaseUrl: 'http://localhost:3001' }; const clinicId = '33333333-3333-4333-8333-333333333333'; const otherId = '44444444-4444-4444-8444-444444444444'; const branchId = '55555555-5555-4555-8555-555555555555';
const owner: AuthorizationContext = { user: { id: 'user', email: 'owner@test', name: 'Owner', platformRole: null }, strategies: ['clinicMember'], clinicMemberships: [{ clinicId, branchId: null, role: 'clinic_owner', dentistId: null }] };
let app: FastifyInstance | undefined; afterEach(async () => { await app?.close(); app = undefined; }); const auth = (context: AuthorizationContext | null): AuthServices => ({ handler: vi.fn(async () => new Response()), getSession: vi.fn(async () => context ? { session: { id: 's', userId: context.user.id, expiresAt: new Date('2030-01-01') }, user: context.user } : null), resolveAuthorization: vi.fn(async () => context) });
const settings = (): ClinicSettingsService => ({ get: vi.fn(async (id) => ({ id, name: 'Smile Bright', slug: 'smile-bright', publicationStatus: 'draft', heroText: null, description: null, email: null, phone: null, website: null, address: null, city: null, province: null, mapUrl: null, facebookUrl: null, instagramUrl: null, branches: [{ id: branchId, name: 'Main', operatingHours: {}, address: null, city: null, province: null, mapUrl: null }] })), updateProfile: vi.fn(async (id) => ({ id })), updateBranchHours: vi.fn(async (_clinic, id, operatingHours) => ({ id, operatingHours })), updateBranchLocation: vi.fn(async (_clinic, id) => ({ id })) });
const publication = (): AdminClinicSettingsService => ({ assignPackage: vi.fn(), setFeatureOverride: vi.fn(), removeFeatureOverride: vi.fn(), updatePublication: vi.fn(async (id, publicationStatus) => ({ id, publicationStatus, updatedAt: new Date() })) });
async function setup(context: AuthorizationContext | null, clinicSettings: ClinicSettingsService, pub = publication()) { app = await buildApp({ config, checkDatabase: async () => undefined, logger: false, auth: auth(context), clinicSettings, adminClinicSettings: pub }); return pub; }
describe('clinic microsite settings routes', () => {
 it('returns the tenant settings to its Clinic Owner', async () => { const service = settings(); await setup(owner, service); const response = await app!.inject({ method: 'GET', url: `/v1/clinic/${clinicId}/settings` }); expect(response.statusCode).toBe(200); expect(service.get).toHaveBeenCalledWith(clinicId); });
 it('denies cross-tenant settings access before querying', async () => { const service = settings(); await setup(owner, service); const response = await app!.inject({ method: 'GET', url: `/v1/clinic/${otherId}/settings` }); expect(response.statusCode).toBe(403); expect(service.get).not.toHaveBeenCalled(); });
 it('strictly validates profile content and prevents tenant injection', async () => { const service = settings(); await setup(owner, service); const response = await app!.inject({ method: 'PATCH', url: `/v1/clinic/${clinicId}/settings`, payload: { heroText: 'Healthy smiles', clinicId: otherId } }); expect(response.statusCode).toBe(400); expect(service.updateProfile).not.toHaveBeenCalled(); });
 it('updates only a clinic-scoped branch hours record', async () => { const service = settings(); await setup(owner, service); const operatingHours = { monday: '9:00 AM–5:00 PM', tuesday: '9:00 AM–5:00 PM', wednesday: '9:00 AM–5:00 PM', thursday: '9:00 AM–5:00 PM', friday: '9:00 AM–5:00 PM', saturday: '9:00 AM–1:00 PM', sunday: 'Closed' }; const response = await app!.inject({ method: 'PATCH', url: `/v1/clinic/${clinicId}/branches/${branchId}/hours`, payload: { operatingHours } }); expect(response.statusCode).toBe(200); expect(service.updateBranchHours).toHaveBeenCalledWith(clinicId, branchId, operatingHours, expect.objectContaining({ id: owner.user.id })); });
 it('uses the entitlement-aware publication service', async () => { const service = settings(); const pub = await setup(owner, service); const response = await app!.inject({ method: 'PATCH', url: `/v1/clinic/${clinicId}/publication`, payload: { publicationStatus: 'published' } }); expect(response.statusCode).toBe(200); expect(pub.updatePublication).toHaveBeenCalledWith(clinicId, 'published', expect.objectContaining({ id: owner.user.id })); });
 it('updates a clinic-scoped branch location, including its Google Maps link', async () => { const service = settings(); await setup(owner, service); const location = { address: '123 Sample St', city: 'Manila', province: 'Metro Manila', mapUrl: 'https://maps.google.com/?q=123+Sample+St' }; const response = await app!.inject({ method: 'PATCH', url: `/v1/clinic/${clinicId}/branches/${branchId}/location`, payload: location }); expect(response.statusCode).toBe(200); expect(service.updateBranchLocation).toHaveBeenCalledWith(clinicId, branchId, location, expect.objectContaining({ id: owner.user.id })); });
 it('rejects a branch location update with an invalid map URL', async () => { const service = settings(); await setup(owner, service); const response = await app!.inject({ method: 'PATCH', url: `/v1/clinic/${clinicId}/branches/${branchId}/location`, payload: { mapUrl: 'not-a-url' } }); expect(response.statusCode).toBe(400); expect(service.updateBranchLocation).not.toHaveBeenCalled(); });
});
