import { afterEach, describe, expect, it, vi } from 'vitest';
import type { FastifyInstance } from 'fastify';
import { FeatureKey } from '@dentra/shared';
import { buildApp } from '../src/app.js';
import type { ClinicPatientsService } from '../src/clinic/patients-service.js';
import type { EntitlementService } from '../src/entitlements/service.js';
import type { AuthServices, AuthorizationContext } from '../src/auth/types.js';
import type { ApiConfig } from '../src/config.js';
const config: ApiConfig = { nodeEnv: 'test', host: '127.0.0.1', port: 3001, logLevel: 'silent', corsOrigins: [], authSecret: 'test-secret-that-is-at-least-32-characters', authBaseUrl: 'http://localhost:3001' };
const clinicId = '00000000-0000-0000-0000-000000000101'; const otherClinicId = '00000000-0000-0000-0000-000000000201'; const patientId = '00000000-0000-0000-0000-000000000301';
const member: AuthorizationContext = { user: { id: 'user', email: 'staff@test', name: 'Staff User', platformRole: null }, strategies: ['clinicMember'], clinicMemberships: [{ clinicId, branchId: null, role: 'clinic_admin', dentistId: null }] };
const auth = (context: AuthorizationContext | null): AuthServices => ({ handler: vi.fn(async () => new Response()), getSession: vi.fn(async () => context ? { session: { id: 'session', userId: context.user.id, expiresAt: new Date('2030-01-01') }, user: context.user } : null), resolveAuthorization: vi.fn(async () => context) });
const entitlements = (enabled = true): EntitlementService => ({ resolve: vi.fn(async (id) => ({ clinic: { id, name: 'Clinic', status: 'active' }, subscription: null, entitlements: [FeatureKey.PATIENTS_MANAGE, FeatureKey.CLINICAL_RECORDS].map((featureKey) => ({ featureKey, isEnabled: enabled, source: 'package' as const, expiresAt: null })) })) });
function patientsService(): ClinicPatientsService { return { list: vi.fn(async () => ({ items: [], pagination: { page: 1, pageSize: 20, total: 0, totalPages: 1 } })), create: vi.fn(async () => ({ id: patientId, patientNumber: 'SBD000041' })), detail: vi.fn(async () => ({ patient: { id: patientId }, appointments: [], medicalHistory: { current: null, versions: [] }, dentalHistory: { current: null, versions: [] } })), addMedicalHistory: vi.fn(async () => ({ id: patientId, createdAt: new Date() })), addDentalHistory: vi.fn(async () => ({ id: patientId, createdAt: new Date() })) }; }
let app: FastifyInstance | undefined; afterEach(async () => { await app?.close(); app = undefined; });
async function setup(context: AuthorizationContext | null, service: ClinicPatientsService, entitlement = entitlements()) { app = await buildApp({ config, checkDatabase: async () => undefined, logger: false, auth: auth(context), entitlements: entitlement, clinicPatients: service }); }
describe('clinic patient routes', () => {
  it('lists only the authenticated clinic scope', async () => { const service = patientsService(); await setup(member, service); const response = await app!.inject({ method: 'GET', url: `/v1/clinic/patients?clinicId=${clinicId}&search=ana&page=1` }); expect(response.statusCode).toBe(200); expect(service.list).toHaveBeenCalledWith(clinicId, { clinicId, search: 'ana', page: 1, pageSize: 20 }); });
  it('creates a patient without accepting a client patient number or clinic body field', async () => { const service = patientsService(); await setup(member, service); const good = await app!.inject({ method: 'POST', url: `/v1/clinic/patients?clinicId=${clinicId}`, payload: { firstName: 'Ana', lastName: 'Santos', phone: '09170000000' } }); const bad = await app!.inject({ method: 'POST', url: `/v1/clinic/patients?clinicId=${clinicId}`, payload: { firstName: 'Ana', lastName: 'Santos', patientNumber: 'HACK001' } }); expect(good.statusCode).toBe(201); expect(good.json().data.patientNumber).toBe('SBD000041'); expect(bad.statusCode).toBe(400); });
  it('returns a profile with versioned histories and appointments', async () => { const service = patientsService(); await setup(member, service); const response = await app!.inject({ method: 'GET', url: `/v1/clinic/patients/${patientId}?clinicId=${clinicId}&appointmentSort=asc` }); expect(response.statusCode).toBe(200); expect(service.detail).toHaveBeenCalledWith(clinicId, patientId, 'asc'); });
  it('appends medical and dental history versions', async () => { const service = patientsService(); await setup(member, service); const medical = await app!.inject({ method: 'POST', url: `/v1/clinic/patients/${patientId}/medical-history?clinicId=${clinicId}`, payload: { allergies: 'None', isPregnant: 'not_applicable' } }); const dental = await app!.inject({ method: 'POST', url: `/v1/clinic/patients/${patientId}/dental-history?clinicId=${clinicId}`, payload: { hasPain: 'no', chiefConcerns: 'Cleaning' } }); expect(medical.statusCode).toBe(201); expect(dental.statusCode).toBe(201); expect(service.addMedicalHistory).toHaveBeenCalledOnce(); expect(service.addDentalHistory).toHaveBeenCalledOnce(); });
  it('denies cross-tenant and unavailable-feature requests before patient queries', async () => { const service = patientsService(); await setup(member, service); const crossTenant = await app!.inject({ method: 'GET', url: `/v1/clinic/patients?clinicId=${otherClinicId}` }); expect(crossTenant.statusCode).toBe(403); expect(service.list).not.toHaveBeenCalled(); await app!.close(); app = undefined; const disabledService = patientsService(); await setup(member, disabledService, entitlements(false)); const unavailable = await app!.inject({ method: 'GET', url: `/v1/clinic/patients?clinicId=${clinicId}` }); expect(unavailable.statusCode).toBe(403); expect(unavailable.json().error.code).toBe('ENTITLEMENT_REQUIRED'); expect(disabledService.list).not.toHaveBeenCalled(); });
});
