'use client'; import { useState, type ChangeEvent, type FormEvent } from 'react'; import { useRouter } from 'next/navigation'; import { AlertCircle, CheckCircle2, Clock3, Eye, EyeOff, ImagePlus, Loader2, Save } from 'lucide-react'; import type { ClinicSettings } from '@/lib/clinic-settings'; import { brandingImageUrl, themeGradientClass } from '@/lib/clinic-branding';
const themePresets = [{ value: 'violet-clean', label: 'Violet Clean' }, { value: 'lavender-soft', label: 'Lavender Soft' }, { value: 'midnight-violet', label: 'Midnight Violet' }] as const;
const weekdays = [{ weekday: 1, label: 'Monday' }, { weekday: 2, label: 'Tuesday' }, { weekday: 3, label: 'Wednesday' }, { weekday: 4, label: 'Thursday' }, { weekday: 5, label: 'Friday' }, { weekday: 6, label: 'Saturday' }, { weekday: 0, label: 'Sunday' }] as const;
const input = 'mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100';
const minutesToTime = (value: number | null): string => { if (value == null) return ''; const h = String(Math.floor(value / 60)).padStart(2, '0'); const m = String(value % 60).padStart(2, '0'); return `${h}:${m}`; };
const timeToMinutes = (value: string): number | null => { const match = /^(\d{2}):(\d{2})$/.exec(value); if (!match) return null; return Number(match[1]) * 60 + Number(match[2]); };

export default function ClinicMicrositeSettings({ clinicId, settings }: { clinicId: string; settings: ClinicSettings }) {
 const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [confirmPublication, setConfirmPublication] = useState(false);
 async function request(path: string, method: string, body: object | null, key: string) { setBusy(key); setError(null); setMessage(null); const response = await fetch(path, { method, headers: body ? { 'content-type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }).catch(() => null); if (!response?.ok) { const payload = response ? await response.json().catch(() => ({})) as { error?: { message?: string } } : {}; setError(payload.error?.message ?? 'Unable to save the clinic settings.'); setBusy(null); return false; } setBusy(null); setMessage('Changes saved successfully.'); router.refresh(); return true; }
 async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await request(`/api/clinic/${clinicId}/settings`, 'PATCH', data, 'profile'); }
 async function saveBranch(event: FormEvent<HTMLFormElement>, branchId: string) {
  event.preventDefault(); const data = new FormData(event.currentTarget);
  const hours = weekdays.map(({ weekday }) => { const isClosed = data.get(`closed-${weekday}`) === 'on'; const opensAt = timeToMinutes(String(data.get(`opens-${weekday}`) ?? '')); const closesAt = timeToMinutes(String(data.get(`closes-${weekday}`) ?? '')); return { weekday, isClosed, opensAt: isClosed ? null : opensAt, closesAt: isClosed ? null : closesAt }; });
  const location = { address: String(data.get('address') ?? '').trim(), city: String(data.get('city') ?? '').trim(), province: String(data.get('province') ?? '').trim(), mapUrl: String(data.get('mapUrl') ?? '').trim() };
  await request(`/api/clinic/${clinicId}/branches/${branchId}/hours`, 'PATCH', { hours }, branchId) && await request(`/api/clinic/${clinicId}/branches/${branchId}/location`, 'PATCH', location, branchId);
 }
 async function updatePublication() { const next = settings.publicationStatus === 'published' ? 'unpublished' : 'published'; if (await request(`/api/clinic/${clinicId}/publication`, 'PATCH', { publicationStatus: next }, 'publication')) setConfirmPublication(false); }
 async function uploadImage(kind: 'logo' | 'cover', event: ChangeEvent<HTMLInputElement>) {
  const file = event.target.files?.[0]; event.target.value = ''; if (!file) return;
  setBusy(kind); setError(null); setMessage(null);
  const formData = new FormData(); formData.append('file', file);
  const response = await fetch(`/api/clinic/${clinicId}/branding/${kind}`, { method: 'POST', body: formData }).catch(() => null);
  if (!response?.ok) { const payload = response ? await response.json().catch(() => ({})) as { error?: { message?: string } } : {}; setError(payload.error?.message ?? `Unable to upload the ${kind}.`); setBusy(null); return; }
  setBusy(null); setMessage('Image uploaded successfully.'); router.refresh();
 }
 async function saveCoverMode(coverMode: 'image' | 'gradient') { await request(`/api/clinic/${clinicId}/settings`, 'PATCH', { coverMode }, 'cover-mode'); }
 const logoSrc = brandingImageUrl(clinicId, 'logo', settings.logoUpdatedAt, settings.logoUrl);
 const coverSrc = brandingImageUrl(clinicId, 'cover', settings.coverUpdatedAt, settings.coverUrl);

 return <div className="space-y-6">{message && <div role="status" className="flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 size={17} />{message}</div>}{error && <div role="alert" className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={17} />{error}</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Microsite publication</h2><p className="mt-1 text-sm text-slate-500">Current state: <span className="font-semibold capitalize">{settings.publicationStatus}</span></p></div>{confirmPublication ? <div className="flex items-center gap-2"><button type="button" onClick={() => setConfirmPublication(false)} className="h-9 rounded-lg border px-3 text-xs font-semibold">Cancel</button><button type="button" disabled={busy === 'publication'} onClick={() => void updatePublication()} className="inline-flex h-9 items-center gap-2 rounded-lg bg-violet-600 px-3 text-xs font-semibold text-white">{busy === 'publication' && <Loader2 size={14} className="animate-spin" />}Confirm</button></div> : <button type="button" onClick={() => setConfirmPublication(true)} className="inline-flex h-9 items-center gap-2 rounded-lg border border-violet-200 px-3 text-xs font-semibold text-violet-700">{settings.publicationStatus === 'published' ? <EyeOff size={15} /> : <Eye size={15} />}{settings.publicationStatus === 'published' ? 'Unpublish' : 'Request publication'}</button>}</div>{confirmPublication && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Publication requires an operational clinic and the effective microsite entitlement. The action is audited.</p>}</section>
 <form onSubmit={saveProfile} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Public profile content</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Hero text</span><input name="heroText" defaultValue={settings.heroText ?? ''} maxLength={300} className={input} /></label><label className="sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Description</span><textarea name="description" defaultValue={settings.description ?? ''} maxLength={5000} rows={5} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-violet-400" /></label>{(['email','phone','website','address','city','province','mapUrl','facebookUrl','instagramUrl'] as const).map((key) => <label key={key} className={key === 'address' ? 'sm:col-span-2' : ''}><span className="text-sm font-semibold capitalize text-slate-700">{key.replace(/Url$/, ' URL')}</span><input type={key === 'email' ? 'email' : key.toLowerCase().includes('url') || key === 'website' ? 'url' : 'text'} name={key} defaultValue={settings[key] ?? ''} className={input} /></label>)}<label><span className="text-sm font-semibold text-slate-700">Theme preset</span><select name="themePreset" defaultValue={settings.themePreset ?? 'violet-clean'} className={input}>{themePresets.map((preset) => <option key={preset.value} value={preset.value}>{preset.label}</option>)}</select></label><label><span className="text-sm font-semibold text-slate-700">Brand accent color</span><input type="color" name="brandAccent" defaultValue={settings.brandAccent ?? '#7C3AED'} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-2" /></label></div><button type="submit" disabled={busy === 'profile'} className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white disabled:bg-violet-300">{busy === 'profile' ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />}Save profile</button></form>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ImagePlus size={17} className="text-violet-600" /><h2 className="font-bold text-slate-900">Branding</h2></div><p className="mt-1 text-sm text-slate-500">Upload a logo and a cover banner for your public page, or skip the cover photo and use a color gradient from your theme preset instead.</p>
  <div className="mt-4 grid gap-6 sm:grid-cols-2">
   <div><span className="text-xs font-semibold text-slate-600">Logo</span><div className="mt-2 flex items-center gap-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-slate-200 bg-slate-50">{logoSrc ? <img src={logoSrc} alt="Clinic logo" className="h-full w-full object-cover" /> : <span className="text-xs text-slate-400">No logo</span>}</div><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-violet-200 px-3 text-xs font-semibold text-violet-700 hover:bg-violet-50">{busy === 'logo' && <Loader2 size={14} className="animate-spin" />}Upload logo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy === 'logo'} onChange={(event) => void uploadImage('logo', event)} className="hidden" /></label></div><p className="mt-2 text-xs text-slate-400">JPEG, PNG, or WebP — up to 5 MB.</p></div>
   <div><span className="text-xs font-semibold text-slate-600">Cover banner</span><div className="mt-2 flex items-center gap-2 text-xs font-semibold text-slate-600"><label className="flex items-center gap-1.5"><input type="radio" name="coverMode" checked={(settings.coverMode ?? 'gradient') === 'gradient'} onChange={() => void saveCoverMode('gradient')} className="h-3.5 w-3.5" />Color / gradient</label><label className="flex items-center gap-1.5"><input type="radio" name="coverMode" checked={settings.coverMode === 'image'} onChange={() => void saveCoverMode('image')} className="h-3.5 w-3.5" />Uploaded image</label></div>
    {(settings.coverMode ?? 'gradient') === 'gradient'
     ? <div className={`mt-3 h-20 w-full rounded-2xl bg-gradient-to-br ${themeGradientClass(settings.themePreset)}`} />
     : <div className="mt-3 flex items-center gap-4"><div className="flex h-20 w-32 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-slate-200 bg-slate-50">{coverSrc ? <img src={coverSrc} alt="Cover banner" className="h-full w-full object-cover" /> : <span className="text-xs text-slate-400">No cover</span>}</div><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-violet-200 px-3 text-xs font-semibold text-violet-700 hover:bg-violet-50">{busy === 'cover' && <Loader2 size={14} className="animate-spin" />}Upload cover<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy === 'cover'} onChange={(event) => void uploadImage('cover', event)} className="hidden" /></label></div>}
    <p className="mt-2 text-xs text-slate-400">Banner works best around 1600×500px, up to 5 MB.</p>
   </div>
  </div>
 </section>
 <section className="space-y-4"><div><h2 className="text-lg font-bold text-slate-900">Branch location &amp; hours</h2><p className="text-sm text-slate-500">Set each branch&apos;s address and Google Maps link, plus its weekly opening and closing time.</p></div>{settings.branches.map((branch) => { const byWeekday = new Map(branch.hours.map((row) => [row.weekday, row])); return <form key={branch.id} onSubmit={(event) => void saveBranch(event, branch.id)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><Clock3 size={17} className="text-violet-600" />{branch.name}</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-xs font-semibold text-slate-600">Address</span><input name="address" defaultValue={branch.address ?? ''} maxLength={1000} className={input} /></label><label><span className="text-xs font-semibold text-slate-600">City</span><input name="city" defaultValue={branch.city ?? ''} maxLength={100} className={input} /></label><label><span className="text-xs font-semibold text-slate-600">Province</span><input name="province" defaultValue={branch.province ?? ''} maxLength={100} className={input} /></label><label className="sm:col-span-2"><span className="text-xs font-semibold text-slate-600">Google Maps link</span><input type="url" name="mapUrl" defaultValue={branch.mapUrl ?? ''} maxLength={500} placeholder="https://maps.google.com/?q=..." className={input} /></label></div><div className="mt-4 space-y-2 border-t border-slate-100 pt-4">{weekdays.map(({ weekday, label: dayLabel }) => { const row = byWeekday.get(weekday); const closed = row?.isClosed ?? weekday === 0; return <div key={weekday} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-100 p-2.5"><span className="w-24 text-xs font-semibold text-slate-600">{dayLabel}</span><label className="flex items-center gap-1.5 text-xs text-slate-500"><input type="checkbox" name={`closed-${weekday}`} defaultChecked={closed} className="h-3.5 w-3.5 rounded border-slate-300" />Closed</label><input type="time" name={`opens-${weekday}`} defaultValue={minutesToTime(row?.opensAt ?? 540)} className="h-9 rounded-lg border border-slate-200 px-2 text-xs" /><span className="text-xs text-slate-400">to</span><input type="time" name={`closes-${weekday}`} defaultValue={minutesToTime(row?.closesAt ?? 1020)} className="h-9 rounded-lg border border-slate-200 px-2 text-xs" /></div>; })}</div><button type="submit" disabled={busy === branch.id} className="mt-5 inline-flex h-10 items-center gap-2 rounded-xl border border-violet-200 px-4 text-sm font-semibold text-violet-700 disabled:opacity-50">{busy === branch.id && <Loader2 size={15} className="animate-spin" />}Save branch</button></form>; })}</section>
 </div>;
}
