import { and, count, eq, inArray, sql } from 'drizzle-orm';
import type { DB } from '@dentra/db';
import { appointments, clinicSubscriptions, clinics, invoices, organizationClinics, organizationMemberships, organizations, patients } from '@dentra/db/schema';
import { writeAudit } from '@dentra/db/audit';
import { AuditAction } from '@dentra/shared';
export type OrganizationService = ReturnType<typeof createOrganizationService>;
export class OrganizationError extends Error { constructor(public code: string, message: string, public statusCode = 400) { super(message); } }
export function createOrganizationService(database: DB) { const member = async (organizationId: string, userId: string) => { const [row] = await database.select({ id: organizationMemberships.id, role: organizationMemberships.role, branchIds: organizationMemberships.branchIds }).from(organizationMemberships).where(and(eq(organizationMemberships.organizationId, organizationId), eq(organizationMemberships.userId, userId))).limit(1); return row ?? null; }; return {
  create: async (input: { name: string; slug: string; clinicId: string }, actor: { id: string; email: string }) => database.transaction(async (tx) => { const [organization] = await tx.insert(organizations).values({ name: input.name, slug: input.slug }).returning({ id: organizations.id }); await tx.insert(organizationClinics).values({ organizationId: organization.id, clinicId: input.clinicId }); await tx.insert(organizationMemberships).values({ organizationId: organization.id, userId: actor.id, role: 'owner', branchIds: '[]' }); await writeAudit(tx as unknown as DB, { actorId: actor.id, actorEmail: actor.email, clinicId: input.clinicId, entityType: 'organization', entityId: organization.id, action: AuditAction.ORGANIZATION_CREATED, metadata: JSON.stringify({ clinicId: input.clinicId }) }); return organization; }),
  attachClinic: async (organizationId: string, clinicId: string, actor: { id: string; email: string }) => { const access = await member(organizationId, actor.id); if (!access || !['owner', 'admin'].includes(access.role)) throw new OrganizationError('FORBIDDEN', 'Organization administrator access is required', 403); const [created] = await database.insert(organizationClinics).values({ organizationId, clinicId }).onConflictDoNothing().returning({ id: organizationClinics.id }); return created ?? { id: 'already-attached' }; },
  listMine: async (userId: string) => { const rows = await database.select({ id: organizations.id, name: organizations.name, slug: organizations.slug, role: organizationMemberships.role, clinicId: organizationClinics.clinicId, clinicName: clinics.name }).from(organizationMemberships).innerJoin(organizations, eq(organizationMemberships.organizationId, organizations.id)).innerJoin(organizationClinics, eq(organizationClinics.organizationId, organizations.id)).innerJoin(clinics, eq(organizationClinics.clinicId, clinics.id)).where(eq(organizationMemberships.userId, userId)); return rows; },
  report: async (organizationId: string, userId: string) => { const access = await member(organizationId, userId); if (!access) throw new OrganizationError('FORBIDDEN', 'Organization access is required', 403); const clinicRows = await database.select({ clinicId: organizationClinics.clinicId }).from(organizationClinics).where(eq(organizationClinics.organizationId, organizationId)); const ids = clinicRows.map((row) => row.clinicId); if (!ids.length) return { clinicCount: 0, appointments: 0, patients: 0, revenuePhp: '0' }; const [[appointmentTotal], [patientTotal], [revenue]] = await Promise.all([database.select({ count: count(appointments.id) }).from(appointments).where(inArray(appointments.clinicId, ids)), database.select({ count: count(patients.id) }).from(patients).where(inArray(patients.clinicId, ids)), database.select({ total: sql<string>`coalesce(sum(${invoices.totalAmountPhp}), 0)::numeric` }).from(invoices).where(inArray(invoices.clinicId, ids))]); return { clinicCount: ids.length, appointments: Number(appointmentTotal?.count ?? 0), patients: Number(patientTotal?.count ?? 0), revenuePhp: revenue?.total ?? '0' }; },
}; }
